; ================================================================
; SID instrument: violin_tpe
; Auto-generated by sidmatch.encoders.raw_asm - do not edit by hand.
;
;   waveform         = 'saw' (mask=$20)
;   adsr             = A=10 D=9 S=8 R=2
;   pulse_width      = 1707 (pw_start=1707 pw_delta=-50 pw_mode=sweep)
;   filter           = mode='off' cutoff_start=44 cutoff_end=44 sweep_frames=50 res=8 voice1=0
;   wavetable        = attack_wf='pulse+saw' sustain_wf='saw' attack_frames=2 test_bit=False
;   ring_mod=0 sync=0 volume=15
;   frequency        = 440.0 Hz (sid_reg=$1d45)
;   gate_frames=67 release_frames=10
; ================================================================

; @meta waveform=saw
; @meta attack=10
; @meta decay=9
; @meta sustain=8
; @meta release=2
; @meta pulse_width=1707
; @meta filter_cutoff=44
; @meta filter_resonance=8
; @meta filter_mode=off
; @meta filter_voice1=0
; @meta ring_mod=0
; @meta sync=0
; @meta frequency=440.0
; @meta gate_frames=67
; @meta release_frames=10
; @meta volume=15
; @meta freq_reg=7493
; @meta wt_attack_frames=2
; @meta wt_attack_waveform=pulse+saw
; @meta wt_sustain_waveform=saw
; @meta wt_use_test_bit=0
; @meta pw_start=1707
; @meta pw_delta=-50
; @meta pw_min=0
; @meta pw_max=2665
; @meta pw_mode=sweep
; @meta filter_cutoff_start=44
; @meta filter_cutoff_end=44
; @meta filter_sweep_frames=50
; @meta fitness_score=0.0000
; @meta version=1
; @meta chip_model=8580
; @meta pw_table=
; @meta wavetable=

violin_tpe_adsr:
    !byte $a9           ; attack<<4 | decay
    !byte $82           ; sustain<<4 | release

violin_tpe_wavetable:
    !byte $60, $00 ; attack wf (frame 0)
    !byte $60, $00 ; attack wf (frame 1)
    !byte $60, $00 ; attack wf (frame 2)
    !byte $20, $00 ; sustain wf (frame 3)
    !byte $ff, $00             ; end-of-table marker

violin_tpe_pulsetable:
    !byte $00, $6a ; frame 0, pw=1707
    !byte $01, $67 ; frame 1, pw=1657
    !byte $02, $64 ; frame 2, pw=1607
    !byte $03, $61 ; frame 3, pw=1557
    !byte $04, $5e ; frame 4, pw=1507
    !byte $05, $5b ; frame 5, pw=1457
    !byte $06, $57 ; frame 6, pw=1407
    !byte $07, $54 ; frame 7, pw=1357
    !byte $08, $51 ; frame 8, pw=1307
    !byte $09, $4e ; frame 9, pw=1257
    !byte $0a, $4b ; frame 10, pw=1207
    !byte $0b, $48 ; frame 11, pw=1157
    !byte $0c, $45 ; frame 12, pw=1107
    !byte $0d, $42 ; frame 13, pw=1057
    !byte $0e, $3e ; frame 14, pw=1007
    !byte $0f, $3b ; frame 15, pw=957
    !byte $ff, $00             ; end-of-table marker

violin_tpe_filtertable:
    !byte $05, $80, $00  ; cutoff_hi, res|rt, mode (static)
    !byte $ff, $00, $00        ; end-of-table marker

violin_tpe_freq_lo:  !byte $45
violin_tpe_freq_hi:  !byte $1d
violin_tpe_volume:   !byte $0f
violin_tpe_gate_frames:    !byte $43, $00
violin_tpe_release_frames: !byte $0a, $00

