"""Encode :class:`SidParams` to ACME-includable raw assembly tables.

Output format (GoatTracker-style tables):

* ``<prefix>_wavetable``: pairs of ``(waveform_byte, cmd_byte)`` rows. If the
  patch has no per-frame ``wavetable``, a single row is emitted holding the
  static waveform; otherwise each entry in ``wavetable`` becomes a row
  (``cmd_byte`` is always ``$00`` for now - reserved for future use).
* ``<prefix>_pulsetable``: pairs of ``(speed, target_hi)`` rows where ``speed``
  is ``$00`` for an absolute PW set and ``target_hi`` is the high byte of the
  pulse width (0-255, covering the 4096-step range in 16-step increments).
  If the patch has no ``pw_table``, a single absolute row is emitted holding
  the static pulse width.
* ``<prefix>_filtertable``: triples of ``(cutoff_hi, resonance_routing, mode)``.
  A single row encodes the static filter state.
* ``<prefix>_adsr``: two bytes - ``(attack<<4)|decay``, ``(sustain<<4)|release``.

The header also records the note frequency (as a 16-bit SID freq register),
volume, gate and release frame counts, ring-mod and sync flags so the round
trip parser can recover every :class:`SidParams` field.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Dict, List, Tuple, Union

from ..render import SidParams, _waveform_mask, hz_to_sid_freq, PAL_CLOCK_HZ


def _fmt_byte(v: int) -> str:
    return f"${v & 0xFF:02x}"


def encode_raw_asm(
    params: SidParams,
    label_prefix: str,
    *,
    fitness_score: float | None = None,
    version: int | None = None,
    chip_model: str | None = None,
    source_instrument: str | None = None,
) -> str:
    """Render ``params`` as ACME assembly source.

    The returned text uses ``!byte`` directives and is suitable for
    ``!source``-inclusion by a song driver. Labels are prefixed with
    ``label_prefix``.

    Optional ``fitness_score`` and ``version`` are recorded as ``@meta``
    comment lines when provided.
    """
    if not re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", label_prefix):
        raise ValueError(f"label_prefix {label_prefix!r} is not a valid symbol")

    freq_reg = hz_to_sid_freq(params.frequency, PAL_CLOCK_HZ)
    wf_mask = _waveform_mask(params.waveform)

    lines: List[str] = []
    lines.append("; ================================================================")
    lines.append(f"; SID instrument: {label_prefix}")
    lines.append("; Auto-generated by sidmatch.encoders.raw_asm - do not edit by hand.")
    lines.append(";")
    lines.append(f";   waveform         = {params.waveform!r} (mask=${wf_mask:02x})")
    lines.append(
        f";   adsr             = A={params.attack} D={params.decay} "
        f"S={params.sustain} R={params.release}"
    )
    lines.append(
        f";   pulse_width      = {params.pulse_width} "
        f"(pw_table entries={len(params.pw_table or [])})"
    )
    lines.append(
        f";   filter           = mode={params.filter_mode!r} "
        f"cutoff={params.filter_cutoff} res={params.filter_resonance} "
        f"voice1={int(params.filter_voice1)}"
    )
    lines.append(
        f";   ring_mod={int(params.ring_mod)} sync={int(params.sync)} "
        f"volume={params.volume}"
    )
    lines.append(
        f";   frequency        = {params.frequency} Hz "
        f"(sid_reg=${freq_reg:04x})"
    )
    lines.append(
        f";   gate_frames={params.gate_frames} "
        f"release_frames={params.release_frames}"
    )
    lines.append(
        f";   wavetable entries = {len(params.wavetable or [])}"
    )
    lines.append("; ================================================================")
    lines.append("")

    # ---- Metadata block (machine-readable, parsed back by parse_raw_asm) ----
    # Emitted as plain assembler-comment key=value pairs so the file is still
    # a clean include; the parser keys off the "; @meta " prefix.
    meta = {
        "waveform": params.waveform,
        "attack": params.attack,
        "decay": params.decay,
        "sustain": params.sustain,
        "release": params.release,
        "pulse_width": params.pulse_width,
        "filter_cutoff": params.filter_cutoff,
        "filter_resonance": params.filter_resonance,
        "filter_mode": params.filter_mode,
        "filter_voice1": int(params.filter_voice1),
        "ring_mod": int(params.ring_mod),
        "sync": int(params.sync),
        "frequency": params.frequency,
        "gate_frames": params.gate_frames,
        "release_frames": params.release_frames,
        "volume": params.volume,
        "freq_reg": freq_reg,
    }
    if fitness_score is not None:
        meta["fitness_score"] = f"{fitness_score:.4f}"
    if version is not None:
        meta["version"] = version
    # Use explicit arguments first, then fall back to SidParams fields.
    _chip = chip_model or params.chip_model
    _source = source_instrument or params.source_instrument
    if _chip is not None:
        meta["chip_model"] = _chip
    if _source is not None:
        meta["source_instrument"] = _source
    for k, v in meta.items():
        lines.append(f"; @meta {k}={v}")
    # Tables serialized as json-ish lists for exact round-trip.
    pw_table_repr = ";".join(f"{f},{v}" for f, v in (params.pw_table or []))
    wt_repr = ";".join(f"{f},{v}" for f, v in (params.wavetable or []))
    lines.append(f"; @meta pw_table={pw_table_repr}")
    lines.append(f"; @meta wavetable={wt_repr}")
    lines.append("")

    # ---- ADSR ----
    ad = ((params.attack & 0x0F) << 4) | (params.decay & 0x0F)
    sr = ((params.sustain & 0x0F) << 4) | (params.release & 0x0F)
    lines.append(f"{label_prefix}_adsr:")
    lines.append(f"    !byte {_fmt_byte(ad)}           ; attack<<4 | decay")
    lines.append(f"    !byte {_fmt_byte(sr)}           ; sustain<<4 | release")
    lines.append("")

    # ---- Wavetable ----
    wavetable = params.wavetable or []
    lines.append(f"{label_prefix}_wavetable:")
    if not wavetable:
        lines.append(
            f"    !byte {_fmt_byte(wf_mask)}, $00     ; static waveform, no cmd"
        )
    else:
        for frame, wf_byte in wavetable:
            lines.append(
                f"    !byte {_fmt_byte(wf_byte)}, {_fmt_byte(frame & 0xFF)} "
                f"; frame {frame}"
            )
    lines.append(f"    !byte $ff, $00             ; end-of-table marker")
    lines.append("")

    # ---- Pulsetable ----
    pw_table = params.pw_table or []
    lines.append(f"{label_prefix}_pulsetable:")
    if not pw_table:
        pw_hi = (params.pulse_width >> 4) & 0xFF
        lines.append(
            f"    !byte $00, {_fmt_byte(pw_hi)}       "
            f"; absolute PW = {params.pulse_width}"
        )
    else:
        for frame, pw in pw_table:
            pw_hi = (pw >> 4) & 0xFF
            lines.append(
                f"    !byte {_fmt_byte(frame & 0xFF)}, {_fmt_byte(pw_hi)} "
                f"; frame {frame}, pw={pw}"
            )
    lines.append(f"    !byte $ff, $00             ; end-of-table marker")
    lines.append("")

    # ---- Filtertable ----
    cutoff_hi = (params.filter_cutoff >> 3) & 0xFF
    res_filt = ((params.filter_resonance & 0x0F) << 4) | (
        0x01 if params.filter_voice1 else 0x00
    )
    mode_map = {"off": 0x00, "lp": 0x10, "bp": 0x20, "hp": 0x40}
    mode_byte = mode_map.get((params.filter_mode or "off").lower(), 0x00)
    lines.append(f"{label_prefix}_filtertable:")
    lines.append(
        f"    !byte {_fmt_byte(cutoff_hi)}, {_fmt_byte(res_filt)}, "
        f"{_fmt_byte(mode_byte)}  ; cutoff_hi, res|rt, mode"
    )
    lines.append(f"    !byte $ff, $00, $00        ; end-of-table marker")
    lines.append("")

    # ---- Frequency + volume + gate timing (static constants) ----
    lines.append(f"{label_prefix}_freq_lo:  !byte {_fmt_byte(freq_reg & 0xFF)}")
    lines.append(f"{label_prefix}_freq_hi:  !byte {_fmt_byte((freq_reg >> 8) & 0xFF)}")
    lines.append(f"{label_prefix}_volume:   !byte {_fmt_byte(params.volume & 0x0F)}")
    lines.append(
        f"{label_prefix}_gate_frames:    !byte "
        f"{_fmt_byte(params.gate_frames & 0xFF)}, "
        f"{_fmt_byte((params.gate_frames >> 8) & 0xFF)}"
    )
    lines.append(
        f"{label_prefix}_release_frames: !byte "
        f"{_fmt_byte(params.release_frames & 0xFF)}, "
        f"{_fmt_byte((params.release_frames >> 8) & 0xFF)}"
    )
    lines.append("")

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Round-trip parser
# ---------------------------------------------------------------------------


def parse_raw_asm(path_or_text: Union[str, Path]) -> Dict:
    """Recover the encoded parameters from raw_asm output.

    Reads the ``; @meta`` comment lines and returns a ``dict`` whose keys
    match the :class:`SidParams` field names (plus ``freq_reg``).
    """
    if isinstance(path_or_text, Path) or (
        isinstance(path_or_text, str) and "\n" not in path_or_text and Path(path_or_text).exists()
    ):
        text = Path(path_or_text).read_text()
    else:
        text = str(path_or_text)

    int_fields = {
        "attack", "decay", "sustain", "release", "pulse_width",
        "filter_cutoff", "filter_resonance", "filter_voice1",
        "ring_mod", "sync", "gate_frames", "release_frames",
        "volume", "freq_reg",
    }
    out: Dict = {}
    for line in text.splitlines():
        m = re.match(r"\s*;\s*@meta\s+([A-Za-z_][A-Za-z0-9_]*)=(.*)$", line)
        if not m:
            continue
        key, val = m.group(1), m.group(2).rstrip()
        if key in ("frequency", "fitness_score"):
            out[key] = float(val)
        elif key == "version":
            out[key] = int(val)
        elif key in ("waveform", "filter_mode", "chip_model", "source_instrument"):
            out[key] = val
        elif key == "pw_table":
            out[key] = _parse_pairlist(val)
        elif key == "wavetable":
            out[key] = _parse_pairlist(val)
        elif key in int_fields:
            out[key] = int(val)
        else:
            # unknown field, leave as string
            out[key] = val

    # Convert 0/1 ints back to bools for bool fields.
    for b in ("filter_voice1", "ring_mod", "sync"):
        if b in out:
            out[b] = bool(out[b])
    return out


def _parse_pairlist(s: str) -> List[Tuple[int, int]]:
    if not s.strip():
        return []
    out: List[Tuple[int, int]] = []
    for item in s.split(";"):
        if not item:
            continue
        a, b = item.split(",")
        out.append((int(a), int(b)))
    return out
