"""Encode :class:`SidParams` to ACME-includable raw assembly tables.

Output format (GoatTracker-style tables):

* ``<prefix>_wavetable``: pairs of ``(waveform_byte, cmd_byte)`` rows. Emits
  the actual per-frame wavetable sequence (test bit, attack waveform, sustain
  waveform) rather than a single static entry.
* ``<prefix>_pulsetable``: pairs of ``(speed, target_hi)`` rows encoding the
  PW sweep parameters as per-frame data.
* ``<prefix>_filtertable``: triples of ``(cutoff_hi, resonance_routing, mode)``.
  Encodes the filter sweep as per-frame data.
* ``<prefix>_adsr``: two bytes - ``(attack<<4)|decay``, ``(sustain<<4)|release``.

The header also records all SidParams fields so the round-trip parser can
recover every field.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Dict, List, Tuple, Union

from ..render import (
    SidParams,
    _waveform_mask,
    hz_to_sid_freq,
    PAL_CLOCK_HZ,
    _compute_pw_for_frame,
    _compute_filter_cutoff_for_frame,
    WF_TEST,
    WF_GATE,
    WF_RING_MOD,
    WF_SYNC,
)


def _fmt_byte(v: int) -> str:
    return f"${v & 0xFF:02x}"


def _build_control_byte(params: SidParams, wf_mask: int) -> int:
    """Build control byte with ring_mod/sync but no gate (for table encoding)."""
    cb = wf_mask
    if params.ring_mod:
        cb |= WF_RING_MOD
    if params.sync:
        cb |= WF_SYNC
    return cb & 0xFE  # no gate bit in table


def encode_raw_asm(
    params: SidParams,
    label_prefix: str,
    *,
    fitness_score: float | None = None,
    version: int | None = None,
    chip_model: str | None = None,
    source_instrument: str | None = None,
) -> str:
    """Render ``params`` as ACME assembly source.

    The returned text uses ``!byte`` directives and is suitable for
    ``!source``-inclusion by a song driver. Labels are prefixed with
    ``label_prefix``.

    Emits actual per-frame wavetable, PW sweep, and filter sweep data.
    """
    if not re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", label_prefix):
        raise ValueError(f"label_prefix {label_prefix!r} is not a valid symbol")

    freq_reg = hz_to_sid_freq(params.frequency, PAL_CLOCK_HZ)
    wf_mask = _waveform_mask(params.waveform)

    lines: List[str] = []
    lines.append("; ================================================================")
    lines.append(f"; SID instrument: {label_prefix}")
    lines.append("; Auto-generated by sidmatch.encoders.raw_asm - do not edit by hand.")
    lines.append(";")
    lines.append(f";   waveform         = {params.waveform!r} (mask=${wf_mask:02x})")
    lines.append(
        f";   adsr             = A={params.attack} D={params.decay} "
        f"S={params.sustain} R={params.release}"
    )
    lines.append(
        f";   pulse_width      = {params.pulse_width} "
        f"(pw_start={params.pw_start} pw_delta={params.pw_delta} "
        f"pw_mode={params.pw_mode})"
    )
    lines.append(
        f";   filter           = mode={params.filter_mode!r} "
        f"cutoff_start={params.effective_filter_cutoff_start()} "
        f"cutoff_end={params.effective_filter_cutoff_end()} "
        f"sweep_frames={params.filter_sweep_frames} "
        f"res={params.filter_resonance} "
        f"voice1={int(params.filter_voice1)}"
    )
    lines.append(
        f";   wavetable        = attack_wf={params.effective_attack_waveform()!r} "
        f"sustain_wf={params.effective_sustain_waveform()!r} "
        f"attack_frames={params.wt_attack_frames} "
        f"test_bit={params.wt_use_test_bit}"
    )
    lines.append(
        f";   ring_mod={int(params.ring_mod)} sync={int(params.sync)} "
        f"volume={params.volume}"
    )
    lines.append(
        f";   frequency        = {params.frequency} Hz "
        f"(sid_reg=${freq_reg:04x})"
    )
    lines.append(
        f";   gate_frames={params.gate_frames} "
        f"release_frames={params.release_frames}"
    )
    lines.append("; ================================================================")
    lines.append("")

    # ---- Metadata block (machine-readable, parsed back by parse_raw_asm) ----
    meta = {
        "waveform": params.waveform,
        "attack": params.attack,
        "decay": params.decay,
        "sustain": params.sustain,
        "release": params.release,
        "pulse_width": params.pulse_width,
        "filter_cutoff": params.filter_cutoff,
        "filter_resonance": params.filter_resonance,
        "filter_mode": params.filter_mode,
        "filter_voice1": int(params.filter_voice1),
        "ring_mod": int(params.ring_mod),
        "sync": int(params.sync),
        "frequency": params.frequency,
        "gate_frames": params.gate_frames,
        "release_frames": params.release_frames,
        "volume": params.volume,
        "freq_reg": freq_reg,
        # New fields
        "wt_attack_frames": params.wt_attack_frames,
        "wt_attack_waveform": params.wt_attack_waveform or "",
        "wt_sustain_waveform": params.wt_sustain_waveform or "",
        "wt_use_test_bit": int(params.wt_use_test_bit),
        "pw_start": params.pw_start if params.pw_start is not None else params.pulse_width,
        "pw_delta": params.pw_delta,
        "pw_min": params.pw_min,
        "pw_max": params.pw_max,
        "pw_mode": params.pw_mode,
        "filter_cutoff_start": params.effective_filter_cutoff_start(),
        "filter_cutoff_end": params.effective_filter_cutoff_end(),
        "filter_sweep_frames": params.filter_sweep_frames,
    }
    if fitness_score is not None:
        meta["fitness_score"] = f"{fitness_score:.4f}"
    if version is not None:
        meta["version"] = version
    _chip = chip_model or params.chip_model
    _source = source_instrument or params.source_instrument
    if _chip is not None:
        meta["chip_model"] = _chip
    if _source is not None:
        meta["source_instrument"] = _source
    for k, v in meta.items():
        lines.append(f"; @meta {k}={v}")
    # Legacy table fields for backward compat
    pw_table_repr = ";".join(f"{f},{v}" for f, v in (params.pw_table or []))
    wt_repr = ";".join(f"{f},{v}" for f, v in (params.wavetable or []))
    lines.append(f"; @meta pw_table={pw_table_repr}")
    lines.append(f"; @meta wavetable={wt_repr}")
    lines.append("")

    # ---- ADSR ----
    ad = ((params.attack & 0x0F) << 4) | (params.decay & 0x0F)
    sr = ((params.sustain & 0x0F) << 4) | (params.release & 0x0F)
    lines.append(f"{label_prefix}_adsr:")
    lines.append(f"    !byte {_fmt_byte(ad)}           ; attack<<4 | decay")
    lines.append(f"    !byte {_fmt_byte(sr)}           ; sustain<<4 | release")
    lines.append("")

    # ---- Wavetable (per-frame) ----
    sustain_wf = _waveform_mask(params.effective_sustain_waveform())
    attack_wf_mask = _waveform_mask(params.effective_attack_waveform())
    wt_attack_frames = max(1, params.wt_attack_frames)

    lines.append(f"{label_prefix}_wavetable:")
    # Emit a few frames representing the wavetable sequence
    wt_rows = []
    max_wt_entries = max(wt_attack_frames + 2, 4)  # enough to show the sequence
    for f in range(max_wt_entries):
        if params.wt_use_test_bit and f == 0:
            wf_byte = WF_TEST
            comment = "test bit (reset osc)"
        elif f <= wt_attack_frames:
            wf_byte = _build_control_byte(params, attack_wf_mask)
            comment = f"attack wf (frame {f})"
        else:
            wf_byte = _build_control_byte(params, sustain_wf)
            comment = f"sustain wf (frame {f})"
        # Right column $00 = no pitch change; the tracker controls the note
        # via the frequency registers.  Using any other value here would
        # override the player's pitch (values $01-$5F set absolute notes).
        wt_rows.append((wf_byte, 0x00, comment))

    for wf_byte, cmd, comment in wt_rows:
        lines.append(
            f"    !byte {_fmt_byte(wf_byte)}, {_fmt_byte(cmd)} "
            f"; {comment}"
        )
    lines.append(f"    !byte $ff, $00             ; end-of-table marker")
    lines.append("")

    # ---- Pulsetable (PW sweep) ----
    pw_start_val = params.effective_pw_start()
    pw_delta = params.pw_delta
    pw_min_val = params.pw_min
    pw_max_val = params.pw_max
    pw_mode = params.pw_mode or "sweep"

    lines.append(f"{label_prefix}_pulsetable:")
    if pw_delta == 0:
        # Static PW
        pw_hi = (pw_start_val >> 4) & 0xFF
        lines.append(
            f"    !byte $00, {_fmt_byte(pw_hi)}       "
            f"; absolute PW = {pw_start_val}"
        )
    else:
        # Emit sweep parameters and a few sample frames
        num_pw_entries = min(16, max(4, abs(pw_delta) * 8))
        for f in range(num_pw_entries):
            pw = _compute_pw_for_frame(f, pw_start_val, pw_delta, pw_min_val, pw_max_val, pw_mode)
            pw_hi = (pw >> 4) & 0xFF
            lines.append(
                f"    !byte {_fmt_byte(f & 0xFF)}, {_fmt_byte(pw_hi)} "
                f"; frame {f}, pw={pw}"
            )
    lines.append(f"    !byte $ff, $00             ; end-of-table marker")
    lines.append("")

    # ---- Filtertable (filter sweep) ----
    cutoff_start = params.effective_filter_cutoff_start()
    cutoff_end = params.effective_filter_cutoff_end()
    sweep_frames = params.filter_sweep_frames
    res_filt = ((params.filter_resonance & 0x0F) << 4) | (
        0x01 if params.filter_voice1 else 0x00
    )
    mode_map = {"off": 0x00, "lp": 0x10, "bp": 0x20, "hp": 0x40}
    mode_byte = mode_map.get((params.filter_mode or "off").lower(), 0x00)

    lines.append(f"{label_prefix}_filtertable:")
    if sweep_frames <= 0 or cutoff_start == cutoff_end:
        # Static filter
        cutoff_hi = (cutoff_start >> 3) & 0xFF
        lines.append(
            f"    !byte {_fmt_byte(cutoff_hi)}, {_fmt_byte(res_filt)}, "
            f"{_fmt_byte(mode_byte)}  ; cutoff_hi, res|rt, mode (static)"
        )
    else:
        # Emit a few frames of the sweep
        num_filt_entries = min(16, sweep_frames + 1)
        for f in range(num_filt_entries):
            fc = _compute_filter_cutoff_for_frame(f, cutoff_start, cutoff_end, sweep_frames)
            fc_hi = (fc >> 3) & 0xFF
            lines.append(
                f"    !byte {_fmt_byte(fc_hi)}, {_fmt_byte(res_filt)}, "
                f"{_fmt_byte(mode_byte)}  ; frame {f}, cutoff={fc}"
            )
    lines.append(f"    !byte $ff, $00, $00        ; end-of-table marker")
    lines.append("")

    # ---- Frequency + volume + gate timing (static constants) ----
    lines.append(f"{label_prefix}_freq_lo:  !byte {_fmt_byte(freq_reg & 0xFF)}")
    lines.append(f"{label_prefix}_freq_hi:  !byte {_fmt_byte((freq_reg >> 8) & 0xFF)}")
    lines.append(f"{label_prefix}_volume:   !byte {_fmt_byte(params.volume & 0x0F)}")
    lines.append(
        f"{label_prefix}_gate_frames:    !byte "
        f"{_fmt_byte(params.gate_frames & 0xFF)}, "
        f"{_fmt_byte((params.gate_frames >> 8) & 0xFF)}"
    )
    lines.append(
        f"{label_prefix}_release_frames: !byte "
        f"{_fmt_byte(params.release_frames & 0xFF)}, "
        f"{_fmt_byte((params.release_frames >> 8) & 0xFF)}"
    )
    lines.append("")

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Round-trip parser
# ---------------------------------------------------------------------------


def parse_raw_asm(path_or_text: Union[str, Path]) -> Dict:
    """Recover the encoded parameters from raw_asm output.

    Reads the ``; @meta`` comment lines and returns a ``dict`` whose keys
    match the :class:`SidParams` field names (plus ``freq_reg``).
    """
    if isinstance(path_or_text, Path) or (
        isinstance(path_or_text, str) and "\n" not in path_or_text and Path(path_or_text).exists()
    ):
        text = Path(path_or_text).read_text()
    else:
        text = str(path_or_text)

    int_fields = {
        "attack", "decay", "sustain", "release", "pulse_width",
        "filter_cutoff", "filter_resonance", "filter_voice1",
        "ring_mod", "sync", "gate_frames", "release_frames",
        "volume", "freq_reg",
        # New int fields
        "wt_attack_frames", "wt_use_test_bit",
        "pw_start", "pw_delta", "pw_min", "pw_max",
        "filter_cutoff_start", "filter_cutoff_end", "filter_sweep_frames",
    }
    out: Dict = {}
    for line in text.splitlines():
        m = re.match(r"\s*;\s*@meta\s+([A-Za-z_][A-Za-z0-9_]*)=(.*)$", line)
        if not m:
            continue
        key, val = m.group(1), m.group(2).rstrip()
        if key in ("frequency", "fitness_score"):
            out[key] = float(val)
        elif key == "version":
            out[key] = int(val)
        elif key in ("waveform", "filter_mode", "chip_model", "source_instrument",
                      "wt_attack_waveform", "wt_sustain_waveform", "pw_mode"):
            out[key] = val
        elif key == "pw_table":
            out[key] = _parse_pairlist(val)
        elif key == "wavetable":
            out[key] = _parse_pairlist(val)
        elif key in int_fields:
            out[key] = int(val)
        else:
            # unknown field, leave as string
            out[key] = val

    # Convert 0/1 ints back to bools for bool fields.
    for b in ("filter_voice1", "ring_mod", "sync", "wt_use_test_bit"):
        if b in out:
            out[b] = bool(out[b])
    return out


def _parse_pairlist(s: str) -> List[Tuple[int, int]]:
    if not s.strip():
        return []
    out: List[Tuple[int, int]] = []
    for item in s.split(";"):
        if not item:
            continue
        a, b = item.split(",")
        out.append((int(a), int(b)))
    return out
