; ================================================================
; SID instrument: acoustic_guitar
; Auto-generated by sidmatch.encoders.raw_asm - do not edit by hand.
;
;   waveform         = 'pulse' (mask=$40)
;   adsr             = A=8 D=1 S=7 R=13
;   pulse_width      = 3481 (pw_start=3481 pw_delta=43 pw_mode=sweep)
;   filter           = mode='lp' cutoff_start=65 cutoff_end=67 sweep_frames=30 res=9 voice1=1
;   wavetable        = attack_wf='noise' sustain_wf='pulse' attack_frames=3 test_bit=True
;   ring_mod=0 sync=0 volume=15
;   frequency        = 440.0 Hz (sid_reg=$1d45)
;   gate_frames=11 release_frames=250
; ================================================================

; @meta waveform=pulse
; @meta attack=8
; @meta decay=1
; @meta sustain=7
; @meta release=13
; @meta pulse_width=3481
; @meta filter_cutoff=65
; @meta filter_resonance=9
; @meta filter_mode=lp
; @meta filter_voice1=1
; @meta ring_mod=0
; @meta sync=0
; @meta frequency=440.0
; @meta gate_frames=11
; @meta release_frames=250
; @meta volume=15
; @meta freq_reg=7493
; @meta wt_attack_frames=3
; @meta wt_attack_waveform=noise
; @meta wt_sustain_waveform=pulse
; @meta wt_use_test_bit=1
; @meta pw_start=3481
; @meta pw_delta=43
; @meta pw_min=347
; @meta pw_max=3374
; @meta pw_mode=sweep
; @meta filter_cutoff_start=65
; @meta filter_cutoff_end=67
; @meta filter_sweep_frames=30
; @meta fitness_score=0.0000
; @meta version=6
; @meta chip_model=8580
; @meta source_instrument=Philharmonia Orchestra (CC-BY-SA 3.0)
; @meta pw_table=
; @meta wavetable=

acoustic_guitar_adsr:
    !byte $81           ; attack<<4 | decay
    !byte $7d           ; sustain<<4 | release

acoustic_guitar_wavetable:
    !byte $08, $00 ; test bit (reset osc)
    !byte $80, $00 ; attack wf (frame 1)
    !byte $80, $00 ; attack wf (frame 2)
    !byte $80, $00 ; attack wf (frame 3)
    !byte $40, $00 ; sustain wf (frame 4)
    !byte $ff, $00             ; end-of-table marker

acoustic_guitar_pulsetable:
    !byte $00, $d2 ; frame 0, pw=3374
    !byte $01, $d2 ; frame 1, pw=3374
    !byte $02, $d2 ; frame 2, pw=3374
    !byte $03, $d2 ; frame 3, pw=3374
    !byte $04, $d2 ; frame 4, pw=3374
    !byte $05, $d2 ; frame 5, pw=3374
    !byte $06, $d2 ; frame 6, pw=3374
    !byte $07, $d2 ; frame 7, pw=3374
    !byte $08, $d2 ; frame 8, pw=3374
    !byte $09, $d2 ; frame 9, pw=3374
    !byte $0a, $d2 ; frame 10, pw=3374
    !byte $0b, $d2 ; frame 11, pw=3374
    !byte $0c, $d2 ; frame 12, pw=3374
    !byte $0d, $d2 ; frame 13, pw=3374
    !byte $0e, $d2 ; frame 14, pw=3374
    !byte $0f, $d2 ; frame 15, pw=3374
    !byte $ff, $00             ; end-of-table marker

acoustic_guitar_filtertable:
    !byte $08, $91, $10  ; frame 0, cutoff=65
    !byte $08, $91, $10  ; frame 1, cutoff=65
    !byte $08, $91, $10  ; frame 2, cutoff=65
    !byte $08, $91, $10  ; frame 3, cutoff=65
    !byte $08, $91, $10  ; frame 4, cutoff=65
    !byte $08, $91, $10  ; frame 5, cutoff=65
    !byte $08, $91, $10  ; frame 6, cutoff=65
    !byte $08, $91, $10  ; frame 7, cutoff=65
    !byte $08, $91, $10  ; frame 8, cutoff=66
    !byte $08, $91, $10  ; frame 9, cutoff=66
    !byte $08, $91, $10  ; frame 10, cutoff=66
    !byte $08, $91, $10  ; frame 11, cutoff=66
    !byte $08, $91, $10  ; frame 12, cutoff=66
    !byte $08, $91, $10  ; frame 13, cutoff=66
    !byte $08, $91, $10  ; frame 14, cutoff=66
    !byte $08, $91, $10  ; frame 15, cutoff=66
    !byte $ff, $00, $00        ; end-of-table marker

acoustic_guitar_freq_lo:  !byte $45
acoustic_guitar_freq_hi:  !byte $1d
acoustic_guitar_volume:   !byte $0f
acoustic_guitar_gate_frames:    !byte $0b, $00
acoustic_guitar_release_frames: !byte $fa, $00

