; ================================================================
; SID instrument: acoustic_guitar
; Auto-generated by sidmatch.encoders.raw_asm - do not edit by hand.
;
;   waveform         = 'pulse' (mask=$40)
;   adsr             = A=0 D=9 S=7 R=5
;   pulse_width      = 2747 (pw_start=2747 pw_delta=10 pw_mode=sweep)
;   filter           = mode='lp' cutoff_start=287 cutoff_end=456 sweep_frames=99 res=0 voice1=1
;   wavetable        = attack_wf='pulse' sustain_wf='pulse' attack_frames=4 test_bit=True
;   ring_mod=0 sync=0 volume=15
;   frequency        = 329.63 Hz (sid_reg=$15ed)
;   gate_frames=42 release_frames=13
; ================================================================

; @meta waveform=pulse
; @meta attack=0
; @meta decay=9
; @meta sustain=7
; @meta release=5
; @meta pulse_width=2747
; @meta filter_cutoff=287
; @meta filter_resonance=0
; @meta filter_mode=lp
; @meta filter_voice1=1
; @meta ring_mod=0
; @meta sync=0
; @meta frequency=329.63
; @meta gate_frames=42
; @meta release_frames=13
; @meta volume=15
; @meta freq_reg=5613
; @meta wt_attack_frames=4
; @meta wt_attack_waveform=
; @meta wt_sustain_waveform=pulse
; @meta wt_use_test_bit=1
; @meta pw_start=2747
; @meta pw_delta=10
; @meta pw_min=2708
; @meta pw_max=2886
; @meta pw_mode=sweep
; @meta filter_cutoff_start=287
; @meta filter_cutoff_end=456
; @meta filter_sweep_frames=99
; @meta fitness_score=0.2867
; @meta version=3
; @meta chip_model=8580
; @meta source_instrument=Philharmonia Orchestra, acoustic guitar E4 forte (CC-BY-SA 3.0)
; @meta pw_table=
; @meta wavetable=

acoustic_guitar_adsr:
    !byte $09           ; attack<<4 | decay
    !byte $75           ; sustain<<4 | release

acoustic_guitar_wavetable:
    !byte $08, $00 ; test bit (reset osc)
    !byte $40, $01 ; attack wf (frame 1)
    !byte $40, $02 ; attack wf (frame 2)
    !byte $40, $03 ; attack wf (frame 3)
    !byte $40, $04 ; attack wf (frame 4)
    !byte $40, $05 ; sustain wf (frame 5)
    !byte $ff, $00             ; end-of-table marker

acoustic_guitar_pulsetable:
    !byte $00, $ab ; frame 0, pw=2747
    !byte $01, $ac ; frame 1, pw=2757
    !byte $02, $ac ; frame 2, pw=2767
    !byte $03, $ad ; frame 3, pw=2777
    !byte $04, $ae ; frame 4, pw=2787
    !byte $05, $ae ; frame 5, pw=2797
    !byte $06, $af ; frame 6, pw=2807
    !byte $07, $b0 ; frame 7, pw=2817
    !byte $08, $b0 ; frame 8, pw=2827
    !byte $09, $b1 ; frame 9, pw=2837
    !byte $0a, $b1 ; frame 10, pw=2847
    !byte $0b, $b2 ; frame 11, pw=2857
    !byte $0c, $b3 ; frame 12, pw=2867
    !byte $0d, $b3 ; frame 13, pw=2877
    !byte $0e, $b4 ; frame 14, pw=2886
    !byte $0f, $b4 ; frame 15, pw=2886
    !byte $ff, $00             ; end-of-table marker

acoustic_guitar_filtertable:
    !byte $23, $01, $10  ; frame 0, cutoff=287
    !byte $24, $01, $10  ; frame 1, cutoff=289
    !byte $24, $01, $10  ; frame 2, cutoff=290
    !byte $24, $01, $10  ; frame 3, cutoff=292
    !byte $24, $01, $10  ; frame 4, cutoff=294
    !byte $25, $01, $10  ; frame 5, cutoff=296
    !byte $25, $01, $10  ; frame 6, cutoff=297
    !byte $25, $01, $10  ; frame 7, cutoff=299
    !byte $25, $01, $10  ; frame 8, cutoff=301
    !byte $25, $01, $10  ; frame 9, cutoff=302
    !byte $26, $01, $10  ; frame 10, cutoff=304
    !byte $26, $01, $10  ; frame 11, cutoff=306
    !byte $26, $01, $10  ; frame 12, cutoff=307
    !byte $26, $01, $10  ; frame 13, cutoff=309
    !byte $26, $01, $10  ; frame 14, cutoff=311
    !byte $27, $01, $10  ; frame 15, cutoff=313
    !byte $ff, $00, $00        ; end-of-table marker

acoustic_guitar_freq_lo:  !byte $ed
acoustic_guitar_freq_hi:  !byte $15
acoustic_guitar_volume:   !byte $0f
acoustic_guitar_gate_frames:    !byte $2a, $00
acoustic_guitar_release_frames: !byte $0d, $00

