; ================================================================
; SID instrument: acoustic_guitar
; Auto-generated by sidmatch.encoders.raw_asm - do not edit by hand.
;
;   waveform         = 'pulse' (mask=$40)
;   adsr             = A=5 D=15 S=7 R=7
;   pulse_width      = 1431 (pw_table entries=4)
;   filter           = mode='bp' cutoff=65 res=0 voice1=1
;   ring_mod=0 sync=0 volume=15
;   frequency        = 329.63 Hz (sid_reg=$15ed)
;   gate_frames=50 release_frames=50
;   wavetable entries = 0
; ================================================================

; @meta waveform=pulse
; @meta attack=5
; @meta decay=15
; @meta sustain=7
; @meta release=7
; @meta pulse_width=1431
; @meta filter_cutoff=65
; @meta filter_resonance=0
; @meta filter_mode=bp
; @meta filter_voice1=1
; @meta ring_mod=0
; @meta sync=0
; @meta frequency=329.63
; @meta gate_frames=50
; @meta release_frames=50
; @meta volume=15
; @meta freq_reg=5613
; @meta fitness_score=0.3512
; @meta version=2
; @meta chip_model=8580
; @meta source_instrument=Philharmonia Orchestra, acoustic guitar E4 forte (CC-BY-SA 3.0)
; @meta pw_table=0,1448;16,814;32,3274;49,287
; @meta wavetable=

acoustic_guitar_adsr:
    !byte $5f           ; attack<<4 | decay
    !byte $77           ; sustain<<4 | release

acoustic_guitar_wavetable:
    !byte $40, $00     ; static waveform, no cmd
    !byte $ff, $00             ; end-of-table marker

acoustic_guitar_pulsetable:
    !byte $00, $5a ; frame 0, pw=1448
    !byte $10, $32 ; frame 16, pw=814
    !byte $20, $cc ; frame 32, pw=3274
    !byte $31, $11 ; frame 49, pw=287
    !byte $ff, $00             ; end-of-table marker

acoustic_guitar_filtertable:
    !byte $08, $01, $20  ; cutoff_hi, res|rt, mode
    !byte $ff, $00, $00        ; end-of-table marker

acoustic_guitar_freq_lo:  !byte $ed
acoustic_guitar_freq_hi:  !byte $15
acoustic_guitar_volume:   !byte $0f
acoustic_guitar_gate_frames:    !byte $32, $00
acoustic_guitar_release_frames: !byte $32, $00

