; ================================================================
; SID instrument: acoustic_guitar
; Auto-generated by sidmatch.encoders.raw_asm - do not edit by hand.
;
;   waveform         = 'saw' (mask=$20)
;   adsr             = A=8 D=3 S=15 R=12
;   pulse_width      = 2245 (pw_start=2245 pw_delta=-26 pw_mode=sweep)
;   filter           = mode='lp' cutoff_start=187 cutoff_end=50 sweep_frames=100 res=0 voice1=1
;   wavetable        = attack_wf='saw+triangle' sustain_wf='saw' attack_frames=5 test_bit=False
;   ring_mod=0 sync=0 volume=15
;   frequency        = 440.0 Hz (sid_reg=$1d45)
;   gate_frames=13 release_frames=155
; ================================================================

; @meta waveform=saw
; @meta attack=8
; @meta decay=3
; @meta sustain=15
; @meta release=12
; @meta pulse_width=2245
; @meta filter_cutoff=187
; @meta filter_resonance=0
; @meta filter_mode=lp
; @meta filter_voice1=1
; @meta ring_mod=0
; @meta sync=0
; @meta frequency=440.0
; @meta gate_frames=13
; @meta release_frames=155
; @meta volume=15
; @meta freq_reg=7493
; @meta wt_attack_frames=5
; @meta wt_attack_waveform=saw+triangle
; @meta wt_sustain_waveform=saw
; @meta wt_use_test_bit=0
; @meta pw_start=2245
; @meta pw_delta=-26
; @meta pw_min=1662
; @meta pw_max=3604
; @meta pw_mode=sweep
; @meta filter_cutoff_start=187
; @meta filter_cutoff_end=50
; @meta filter_sweep_frames=100
; @meta fitness_score=0.6985
; @meta version=4
; @meta chip_model=8580
; @meta source_instrument=Philharmonia Orchestra acoustic guitar forte normal
; @meta pw_table=
; @meta wavetable=

acoustic_guitar_adsr:
    !byte $83           ; attack<<4 | decay
    !byte $fc           ; sustain<<4 | release

acoustic_guitar_wavetable:
    !byte $30, $00 ; attack wf (frame 0)
    !byte $30, $00 ; attack wf (frame 1)
    !byte $30, $00 ; attack wf (frame 2)
    !byte $30, $00 ; attack wf (frame 3)
    !byte $30, $00 ; attack wf (frame 4)
    !byte $30, $00 ; attack wf (frame 5)
    !byte $20, $00 ; sustain wf (frame 6)
    !byte $ff, $00             ; end-of-table marker

acoustic_guitar_pulsetable:
    !byte $00, $8c ; frame 0, pw=2245
    !byte $01, $8a ; frame 1, pw=2219
    !byte $02, $89 ; frame 2, pw=2193
    !byte $03, $87 ; frame 3, pw=2167
    !byte $04, $85 ; frame 4, pw=2141
    !byte $05, $84 ; frame 5, pw=2115
    !byte $06, $82 ; frame 6, pw=2089
    !byte $07, $80 ; frame 7, pw=2063
    !byte $08, $7f ; frame 8, pw=2037
    !byte $09, $7d ; frame 9, pw=2011
    !byte $0a, $7c ; frame 10, pw=1985
    !byte $0b, $7a ; frame 11, pw=1959
    !byte $0c, $78 ; frame 12, pw=1933
    !byte $0d, $77 ; frame 13, pw=1907
    !byte $0e, $75 ; frame 14, pw=1881
    !byte $0f, $73 ; frame 15, pw=1855
    !byte $ff, $00             ; end-of-table marker

acoustic_guitar_filtertable:
    !byte $17, $01, $10  ; frame 0, cutoff=187
    !byte $17, $01, $10  ; frame 1, cutoff=186
    !byte $17, $01, $10  ; frame 2, cutoff=184
    !byte $16, $01, $10  ; frame 3, cutoff=183
    !byte $16, $01, $10  ; frame 4, cutoff=182
    !byte $16, $01, $10  ; frame 5, cutoff=180
    !byte $16, $01, $10  ; frame 6, cutoff=179
    !byte $16, $01, $10  ; frame 7, cutoff=177
    !byte $16, $01, $10  ; frame 8, cutoff=176
    !byte $15, $01, $10  ; frame 9, cutoff=175
    !byte $15, $01, $10  ; frame 10, cutoff=173
    !byte $15, $01, $10  ; frame 11, cutoff=172
    !byte $15, $01, $10  ; frame 12, cutoff=171
    !byte $15, $01, $10  ; frame 13, cutoff=169
    !byte $15, $01, $10  ; frame 14, cutoff=168
    !byte $14, $01, $10  ; frame 15, cutoff=166
    !byte $ff, $00, $00        ; end-of-table marker

acoustic_guitar_freq_lo:  !byte $45
acoustic_guitar_freq_hi:  !byte $1d
acoustic_guitar_volume:   !byte $0f
acoustic_guitar_gate_frames:    !byte $0d, $00
acoustic_guitar_release_frames: !byte $9b, $00

