; ================================================================
; SID instrument: acoustic_guitar_tpe
; Auto-generated by sidmatch.encoders.raw_asm - do not edit by hand.
;
;   waveform         = 'saw' (mask=$20)
;   adsr             = A=14 D=15 S=14 R=6
;   pulse_width      = 2048 (pw_start=2048 pw_delta=0 pw_mode=sweep)
;   filter           = mode='lp' cutoff_start=91 cutoff_end=10 sweep_frames=75 res=8 voice1=1
;   wavetable        = attack_wf='saw+triangle' sustain_wf='saw' attack_frames=4 test_bit=True
;   ring_mod=0 sync=0 volume=15
;   frequency        = 440.0 Hz (sid_reg=$1d45)
;   gate_frames=200 release_frames=15
; ================================================================

; @meta waveform=saw
; @meta attack=14
; @meta decay=15
; @meta sustain=14
; @meta release=6
; @meta pulse_width=2048
; @meta filter_cutoff=91
; @meta filter_resonance=8
; @meta filter_mode=lp
; @meta filter_voice1=1
; @meta ring_mod=0
; @meta sync=0
; @meta frequency=440.0
; @meta gate_frames=200
; @meta release_frames=15
; @meta volume=15
; @meta freq_reg=7493
; @meta wt_attack_frames=4
; @meta wt_attack_waveform=saw+triangle
; @meta wt_sustain_waveform=saw
; @meta wt_use_test_bit=1
; @meta pw_start=2048
; @meta pw_delta=0
; @meta pw_min=1024
; @meta pw_max=3071
; @meta pw_mode=sweep
; @meta filter_cutoff_start=91
; @meta filter_cutoff_end=10
; @meta filter_sweep_frames=75
; @meta fitness_score=0.0000
; @meta version=1
; @meta chip_model=8580
; @meta pw_table=
; @meta wavetable=

acoustic_guitar_tpe_adsr:
    !byte $ef           ; attack<<4 | decay
    !byte $e6           ; sustain<<4 | release

acoustic_guitar_tpe_wavetable:
    !byte $08, $00 ; test bit (reset osc)
    !byte $30, $00 ; attack wf (frame 1)
    !byte $30, $00 ; attack wf (frame 2)
    !byte $30, $00 ; attack wf (frame 3)
    !byte $30, $00 ; attack wf (frame 4)
    !byte $20, $00 ; sustain wf (frame 5)
    !byte $ff, $00             ; end-of-table marker

acoustic_guitar_tpe_pulsetable:
    !byte $00, $80       ; absolute PW = 2048
    !byte $ff, $00             ; end-of-table marker

acoustic_guitar_tpe_filtertable:
    !byte $0b, $81, $10  ; frame 0, cutoff=91
    !byte $0b, $81, $10  ; frame 1, cutoff=90
    !byte $0b, $81, $10  ; frame 2, cutoff=89
    !byte $0b, $81, $10  ; frame 3, cutoff=88
    !byte $0a, $81, $10  ; frame 4, cutoff=87
    !byte $0a, $81, $10  ; frame 5, cutoff=86
    !byte $0a, $81, $10  ; frame 6, cutoff=85
    !byte $0a, $81, $10  ; frame 7, cutoff=83
    !byte $0a, $81, $10  ; frame 8, cutoff=82
    !byte $0a, $81, $10  ; frame 9, cutoff=81
    !byte $0a, $81, $10  ; frame 10, cutoff=80
    !byte $09, $81, $10  ; frame 11, cutoff=79
    !byte $09, $81, $10  ; frame 12, cutoff=78
    !byte $09, $81, $10  ; frame 13, cutoff=77
    !byte $09, $81, $10  ; frame 14, cutoff=76
    !byte $09, $81, $10  ; frame 15, cutoff=75
    !byte $ff, $00, $00        ; end-of-table marker

acoustic_guitar_tpe_freq_lo:  !byte $45
acoustic_guitar_tpe_freq_hi:  !byte $1d
acoustic_guitar_tpe_volume:   !byte $0f
acoustic_guitar_tpe_gate_frames:    !byte $c8, $00
acoustic_guitar_tpe_release_frames: !byte $0f, $00

