; ================================================================
; SID instrument: grand_piano
; Auto-generated by sidmatch.encoders.raw_asm - do not edit by hand.
;
;   waveform         = 'saw' (mask=$20)
;   adsr             = A=3 D=7 S=15 R=12
;   pulse_width      = 664 (pw_start=664 pw_delta=15 pw_mode=sweep)
;   filter           = mode='lp' cutoff_start=143 cutoff_end=239 sweep_frames=39 res=12 voice1=1
;   wavetable        = attack_wf='saw+triangle' sustain_wf='saw' attack_frames=1 test_bit=True
;   ring_mod=0 sync=0 volume=15
;   frequency        = 440.0 Hz (sid_reg=$1d45)
;   gate_frames=18 release_frames=155
; ================================================================

; @meta waveform=saw
; @meta attack=3
; @meta decay=7
; @meta sustain=15
; @meta release=12
; @meta pulse_width=664
; @meta filter_cutoff=143
; @meta filter_resonance=12
; @meta filter_mode=lp
; @meta filter_voice1=1
; @meta ring_mod=0
; @meta sync=0
; @meta frequency=440.0
; @meta gate_frames=18
; @meta release_frames=155
; @meta volume=15
; @meta freq_reg=7493
; @meta wt_attack_frames=1
; @meta wt_attack_waveform=saw+triangle
; @meta wt_sustain_waveform=saw
; @meta wt_use_test_bit=1
; @meta pw_start=664
; @meta pw_delta=15
; @meta pw_min=724
; @meta pw_max=3324
; @meta pw_mode=sweep
; @meta filter_cutoff_start=143
; @meta filter_cutoff_end=239
; @meta filter_sweep_frames=39
; @meta fitness_score=0.4658
; @meta version=8
; @meta chip_model=6581
; @meta source_instrument=Salamander Grand Piano (CC-BY 3.0)
; @meta pw_table=
; @meta wavetable=

grand_piano_adsr:
    !byte $37           ; attack<<4 | decay
    !byte $fc           ; sustain<<4 | release

grand_piano_wavetable:
    !byte $08, $00 ; test bit (reset osc)
    !byte $30, $00 ; attack wf (frame 1)
    !byte $20, $00 ; sustain wf (frame 2)
    !byte $20, $00 ; sustain wf (frame 3)
    !byte $ff, $00             ; end-of-table marker

grand_piano_pulsetable:
    !byte $00, $2d ; frame 0, pw=724
    !byte $01, $2d ; frame 1, pw=724
    !byte $02, $2d ; frame 2, pw=724
    !byte $03, $2d ; frame 3, pw=724
    !byte $04, $2d ; frame 4, pw=724
    !byte $05, $2e ; frame 5, pw=739
    !byte $06, $2f ; frame 6, pw=754
    !byte $07, $30 ; frame 7, pw=769
    !byte $08, $31 ; frame 8, pw=784
    !byte $09, $31 ; frame 9, pw=799
    !byte $0a, $32 ; frame 10, pw=814
    !byte $0b, $33 ; frame 11, pw=829
    !byte $0c, $34 ; frame 12, pw=844
    !byte $0d, $35 ; frame 13, pw=859
    !byte $0e, $36 ; frame 14, pw=874
    !byte $0f, $37 ; frame 15, pw=889
    !byte $ff, $00             ; end-of-table marker

grand_piano_filtertable:
    !byte $11, $c1, $10  ; frame 0, cutoff=143
    !byte $12, $c1, $10  ; frame 1, cutoff=145
    !byte $12, $c1, $10  ; frame 2, cutoff=148
    !byte $12, $c1, $10  ; frame 3, cutoff=150
    !byte $13, $c1, $10  ; frame 4, cutoff=153
    !byte $13, $c1, $10  ; frame 5, cutoff=155
    !byte $13, $c1, $10  ; frame 6, cutoff=158
    !byte $14, $c1, $10  ; frame 7, cutoff=160
    !byte $14, $c1, $10  ; frame 8, cutoff=163
    !byte $14, $c1, $10  ; frame 9, cutoff=165
    !byte $15, $c1, $10  ; frame 10, cutoff=168
    !byte $15, $c1, $10  ; frame 11, cutoff=170
    !byte $15, $c1, $10  ; frame 12, cutoff=173
    !byte $15, $c1, $10  ; frame 13, cutoff=175
    !byte $16, $c1, $10  ; frame 14, cutoff=177
    !byte $16, $c1, $10  ; frame 15, cutoff=180
    !byte $ff, $00, $00        ; end-of-table marker

grand_piano_freq_lo:  !byte $45
grand_piano_freq_hi:  !byte $1d
grand_piano_volume:   !byte $0f
grand_piano_gate_frames:    !byte $12, $00
grand_piano_release_frames: !byte $9b, $00

