; ================================================================
; SID instrument: grand_piano
; Auto-generated by sidmatch.encoders.raw_asm - do not edit by hand.
;
;   waveform         = 'saw' (mask=$20)
;   adsr             = A=0 D=0 S=4 R=10
;   pulse_width      = 2048 (pw_start=2048 pw_delta=0 pw_mode=sweep)
;   filter           = mode='off' cutoff_start=44 cutoff_end=44 sweep_frames=50 res=8 voice1=0
;   wavetable        = attack_wf='saw' sustain_wf='saw' attack_frames=5 test_bit=False
;   ring_mod=0 sync=0 volume=15
;   frequency        = 440.0 Hz (sid_reg=$1d45)
;   gate_frames=10 release_frames=80
; ================================================================

; @meta waveform=saw
; @meta attack=0
; @meta decay=0
; @meta sustain=4
; @meta release=10
; @meta pulse_width=2048
; @meta filter_cutoff=44
; @meta filter_resonance=8
; @meta filter_mode=off
; @meta filter_voice1=0
; @meta ring_mod=0
; @meta sync=0
; @meta frequency=440.0
; @meta gate_frames=10
; @meta release_frames=80
; @meta volume=15
; @meta freq_reg=7493
; @meta wt_attack_frames=5
; @meta wt_attack_waveform=
; @meta wt_sustain_waveform=saw
; @meta wt_use_test_bit=0
; @meta pw_start=2048
; @meta pw_delta=0
; @meta pw_min=1024
; @meta pw_max=3071
; @meta pw_mode=sweep
; @meta filter_cutoff_start=44
; @meta filter_cutoff_end=44
; @meta filter_sweep_frames=50
; @meta fitness_score=0.0000
; @meta version=9
; @meta chip_model=6581
; @meta source_instrument=Salamander Grand Piano (CC-BY 3.0)
; @meta pw_table=
; @meta wavetable=

grand_piano_adsr:
    !byte $00           ; attack<<4 | decay
    !byte $4a           ; sustain<<4 | release

grand_piano_wavetable:
    !byte $20, $00 ; attack wf (frame 0)
    !byte $20, $00 ; attack wf (frame 1)
    !byte $20, $00 ; attack wf (frame 2)
    !byte $20, $00 ; attack wf (frame 3)
    !byte $20, $00 ; attack wf (frame 4)
    !byte $20, $00 ; attack wf (frame 5)
    !byte $20, $00 ; sustain wf (frame 6)
    !byte $ff, $00             ; end-of-table marker

grand_piano_pulsetable:
    !byte $00, $80       ; absolute PW = 2048
    !byte $ff, $00             ; end-of-table marker

grand_piano_filtertable:
    !byte $05, $80, $00  ; cutoff_hi, res|rt, mode (static)
    !byte $ff, $00, $00        ; end-of-table marker

grand_piano_freq_lo:  !byte $45
grand_piano_freq_hi:  !byte $1d
grand_piano_volume:   !byte $0f
grand_piano_gate_frames:    !byte $0a, $00
grand_piano_release_frames: !byte $50, $00

