; ================================================================
; SID instrument: grand_piano
; Auto-generated by sidmatch.encoders.raw_asm - do not edit by hand.
;
;   waveform         = 'pulse' (mask=$40)
;   adsr             = A=9 D=10 S=1 R=6
;   pulse_width      = 1977 (pw_start=1977 pw_delta=-13 pw_mode=sweep)
;   filter           = mode='lp' cutoff_start=158 cutoff_end=536 sweep_frames=98 res=15 voice1=1
;   wavetable        = attack_wf='pulse+saw' sustain_wf='pulse' attack_frames=1 test_bit=True
;   ring_mod=0 sync=0 volume=15
;   frequency        = 261.63 Hz (sid_reg=$1167)
;   gate_frames=92 release_frames=15
; ================================================================

; @meta waveform=pulse
; @meta attack=9
; @meta decay=10
; @meta sustain=1
; @meta release=6
; @meta pulse_width=1977
; @meta filter_cutoff=158
; @meta filter_resonance=15
; @meta filter_mode=lp
; @meta filter_voice1=1
; @meta ring_mod=0
; @meta sync=0
; @meta frequency=261.63
; @meta gate_frames=92
; @meta release_frames=15
; @meta volume=15
; @meta freq_reg=4455
; @meta wt_attack_frames=1
; @meta wt_attack_waveform=pulse+saw
; @meta wt_sustain_waveform=pulse
; @meta wt_use_test_bit=1
; @meta pw_start=1977
; @meta pw_delta=-13
; @meta pw_min=2791
; @meta pw_max=2854
; @meta pw_mode=sweep
; @meta filter_cutoff_start=158
; @meta filter_cutoff_end=536
; @meta filter_sweep_frames=98
; @meta fitness_score=0.2593
; @meta version=2
; @meta chip_model=6581
; @meta source_instrument=Salamander Grand Piano V3, C4 fortissimo (CC-BY 3.0, Alexander Holm)
; @meta pw_table=
; @meta wavetable=

grand_piano_adsr:
    !byte $9a           ; attack<<4 | decay
    !byte $16           ; sustain<<4 | release

grand_piano_wavetable:
    !byte $08, $00 ; test bit (reset osc)
    !byte $60, $01 ; attack wf (frame 1)
    !byte $40, $02 ; sustain wf (frame 2)
    !byte $40, $03 ; sustain wf (frame 3)
    !byte $ff, $00             ; end-of-table marker

grand_piano_pulsetable:
    !byte $00, $ae ; frame 0, pw=2791
    !byte $01, $ae ; frame 1, pw=2791
    !byte $02, $ae ; frame 2, pw=2791
    !byte $03, $ae ; frame 3, pw=2791
    !byte $04, $ae ; frame 4, pw=2791
    !byte $05, $ae ; frame 5, pw=2791
    !byte $06, $ae ; frame 6, pw=2791
    !byte $07, $ae ; frame 7, pw=2791
    !byte $08, $ae ; frame 8, pw=2791
    !byte $09, $ae ; frame 9, pw=2791
    !byte $0a, $ae ; frame 10, pw=2791
    !byte $0b, $ae ; frame 11, pw=2791
    !byte $0c, $ae ; frame 12, pw=2791
    !byte $0d, $ae ; frame 13, pw=2791
    !byte $0e, $ae ; frame 14, pw=2791
    !byte $0f, $ae ; frame 15, pw=2791
    !byte $ff, $00             ; end-of-table marker

grand_piano_filtertable:
    !byte $13, $f1, $10  ; frame 0, cutoff=158
    !byte $14, $f1, $10  ; frame 1, cutoff=162
    !byte $14, $f1, $10  ; frame 2, cutoff=166
    !byte $15, $f1, $10  ; frame 3, cutoff=170
    !byte $15, $f1, $10  ; frame 4, cutoff=173
    !byte $16, $f1, $10  ; frame 5, cutoff=177
    !byte $16, $f1, $10  ; frame 6, cutoff=181
    !byte $17, $f1, $10  ; frame 7, cutoff=185
    !byte $17, $f1, $10  ; frame 8, cutoff=189
    !byte $18, $f1, $10  ; frame 9, cutoff=193
    !byte $18, $f1, $10  ; frame 10, cutoff=197
    !byte $19, $f1, $10  ; frame 11, cutoff=200
    !byte $19, $f1, $10  ; frame 12, cutoff=204
    !byte $1a, $f1, $10  ; frame 13, cutoff=208
    !byte $1a, $f1, $10  ; frame 14, cutoff=212
    !byte $1b, $f1, $10  ; frame 15, cutoff=216
    !byte $ff, $00, $00        ; end-of-table marker

grand_piano_freq_lo:  !byte $67
grand_piano_freq_hi:  !byte $11
grand_piano_volume:   !byte $0f
grand_piano_gate_frames:    !byte $5c, $00
grand_piano_release_frames: !byte $0f, $00

