; ================================================================
; SID instrument: grand_piano
; Auto-generated by sidmatch.encoders.raw_asm - do not edit by hand.
;
;   waveform         = 'saw' (mask=$20)
;   adsr             = A=12 D=6 S=9 R=10
;   pulse_width      = 278 (pw_start=278 pw_delta=50 pw_mode=sweep)
;   filter           = mode='lp' cutoff_start=154 cutoff_end=320 sweep_frames=44 res=11 voice1=1
;   wavetable        = attack_wf='saw' sustain_wf='saw' attack_frames=5 test_bit=True
;   ring_mod=0 sync=0 volume=15
;   frequency        = 440.0 Hz (sid_reg=$1d45)
;   gate_frames=65 release_frames=80
; ================================================================

; @meta waveform=saw
; @meta attack=12
; @meta decay=6
; @meta sustain=9
; @meta release=10
; @meta pulse_width=278
; @meta filter_cutoff=154
; @meta filter_resonance=11
; @meta filter_mode=lp
; @meta filter_voice1=1
; @meta ring_mod=0
; @meta sync=0
; @meta frequency=440.0
; @meta gate_frames=65
; @meta release_frames=80
; @meta volume=15
; @meta freq_reg=7493
; @meta wt_attack_frames=5
; @meta wt_attack_waveform=
; @meta wt_sustain_waveform=saw
; @meta wt_use_test_bit=1
; @meta pw_start=278
; @meta pw_delta=50
; @meta pw_min=1790
; @meta pw_max=2208
; @meta pw_mode=sweep
; @meta filter_cutoff_start=154
; @meta filter_cutoff_end=320
; @meta filter_sweep_frames=44
; @meta fitness_score=0.0000
; @meta version=4
; @meta chip_model=6581
; @meta pw_table=
; @meta wavetable=

grand_piano_adsr:
    !byte $c6           ; attack<<4 | decay
    !byte $9a           ; sustain<<4 | release

grand_piano_wavetable:
    !byte $08, $00 ; test bit (reset osc)
    !byte $20, $00 ; attack wf (frame 1)
    !byte $20, $00 ; attack wf (frame 2)
    !byte $20, $00 ; attack wf (frame 3)
    !byte $20, $00 ; attack wf (frame 4)
    !byte $20, $00 ; attack wf (frame 5)
    !byte $20, $00 ; sustain wf (frame 6)
    !byte $ff, $00             ; end-of-table marker

grand_piano_pulsetable:
    !byte $00, $6f ; frame 0, pw=1790
    !byte $01, $6f ; frame 1, pw=1790
    !byte $02, $6f ; frame 2, pw=1790
    !byte $03, $6f ; frame 3, pw=1790
    !byte $04, $6f ; frame 4, pw=1790
    !byte $05, $6f ; frame 5, pw=1790
    !byte $06, $6f ; frame 6, pw=1790
    !byte $07, $6f ; frame 7, pw=1790
    !byte $08, $6f ; frame 8, pw=1790
    !byte $09, $6f ; frame 9, pw=1790
    !byte $0a, $6f ; frame 10, pw=1790
    !byte $0b, $6f ; frame 11, pw=1790
    !byte $0c, $6f ; frame 12, pw=1790
    !byte $0d, $6f ; frame 13, pw=1790
    !byte $0e, $6f ; frame 14, pw=1790
    !byte $0f, $6f ; frame 15, pw=1790
    !byte $ff, $00             ; end-of-table marker

grand_piano_filtertable:
    !byte $13, $b1, $10  ; frame 0, cutoff=154
    !byte $13, $b1, $10  ; frame 1, cutoff=158
    !byte $14, $b1, $10  ; frame 2, cutoff=162
    !byte $14, $b1, $10  ; frame 3, cutoff=165
    !byte $15, $b1, $10  ; frame 4, cutoff=169
    !byte $15, $b1, $10  ; frame 5, cutoff=173
    !byte $16, $b1, $10  ; frame 6, cutoff=177
    !byte $16, $b1, $10  ; frame 7, cutoff=180
    !byte $17, $b1, $10  ; frame 8, cutoff=184
    !byte $17, $b1, $10  ; frame 9, cutoff=188
    !byte $18, $b1, $10  ; frame 10, cutoff=192
    !byte $18, $b1, $10  ; frame 11, cutoff=196
    !byte $18, $b1, $10  ; frame 12, cutoff=199
    !byte $19, $b1, $10  ; frame 13, cutoff=203
    !byte $19, $b1, $10  ; frame 14, cutoff=207
    !byte $1a, $b1, $10  ; frame 15, cutoff=211
    !byte $ff, $00, $00        ; end-of-table marker

grand_piano_freq_lo:  !byte $45
grand_piano_freq_hi:  !byte $1d
grand_piano_volume:   !byte $0f
grand_piano_gate_frames:    !byte $41, $00
grand_piano_release_frames: !byte $50, $00

