; ================================================================
; SID instrument: grand_piano
; Auto-generated by sidmatch.encoders.raw_asm - do not edit by hand.
;
;   waveform         = 'saw' (mask=$20)
;   adsr             = A=5 D=1 S=15 R=12
;   pulse_width      = 530 (pw_start=530 pw_delta=-13 pw_mode=sweep)
;   filter           = mode='lp' cutoff_start=78 cutoff_end=305 sweep_frames=42 res=15 voice1=1
;   wavetable        = attack_wf='pulse+saw' sustain_wf='saw' attack_frames=1 test_bit=False
;   ring_mod=0 sync=0 volume=15
;   frequency        = 440.0 Hz (sid_reg=$1d45)
;   gate_frames=10 release_frames=155
; ================================================================

; @meta waveform=saw
; @meta attack=5
; @meta decay=1
; @meta sustain=15
; @meta release=12
; @meta pulse_width=530
; @meta filter_cutoff=78
; @meta filter_resonance=15
; @meta filter_mode=lp
; @meta filter_voice1=1
; @meta ring_mod=0
; @meta sync=0
; @meta frequency=440.0
; @meta gate_frames=10
; @meta release_frames=155
; @meta volume=15
; @meta freq_reg=7493
; @meta wt_attack_frames=1
; @meta wt_attack_waveform=pulse+saw
; @meta wt_sustain_waveform=saw
; @meta wt_use_test_bit=0
; @meta pw_start=530
; @meta pw_delta=-13
; @meta pw_min=2605
; @meta pw_max=3462
; @meta pw_mode=sweep
; @meta filter_cutoff_start=78
; @meta filter_cutoff_end=305
; @meta filter_sweep_frames=42
; @meta fitness_score=0.0000
; @meta version=3
; @meta chip_model=6581
; @meta pw_table=
; @meta wavetable=

grand_piano_adsr:
    !byte $51           ; attack<<4 | decay
    !byte $fc           ; sustain<<4 | release

grand_piano_wavetable:
    !byte $60, $00 ; attack wf (frame 0)
    !byte $60, $00 ; attack wf (frame 1)
    !byte $20, $00 ; sustain wf (frame 2)
    !byte $20, $00 ; sustain wf (frame 3)
    !byte $ff, $00             ; end-of-table marker

grand_piano_pulsetable:
    !byte $00, $a2 ; frame 0, pw=2605
    !byte $01, $a2 ; frame 1, pw=2605
    !byte $02, $a2 ; frame 2, pw=2605
    !byte $03, $a2 ; frame 3, pw=2605
    !byte $04, $a2 ; frame 4, pw=2605
    !byte $05, $a2 ; frame 5, pw=2605
    !byte $06, $a2 ; frame 6, pw=2605
    !byte $07, $a2 ; frame 7, pw=2605
    !byte $08, $a2 ; frame 8, pw=2605
    !byte $09, $a2 ; frame 9, pw=2605
    !byte $0a, $a2 ; frame 10, pw=2605
    !byte $0b, $a2 ; frame 11, pw=2605
    !byte $0c, $a2 ; frame 12, pw=2605
    !byte $0d, $a2 ; frame 13, pw=2605
    !byte $0e, $a2 ; frame 14, pw=2605
    !byte $0f, $a2 ; frame 15, pw=2605
    !byte $ff, $00             ; end-of-table marker

grand_piano_filtertable:
    !byte $09, $f1, $10  ; frame 0, cutoff=78
    !byte $0a, $f1, $10  ; frame 1, cutoff=83
    !byte $0b, $f1, $10  ; frame 2, cutoff=89
    !byte $0b, $f1, $10  ; frame 3, cutoff=94
    !byte $0c, $f1, $10  ; frame 4, cutoff=100
    !byte $0d, $f1, $10  ; frame 5, cutoff=105
    !byte $0d, $f1, $10  ; frame 6, cutoff=110
    !byte $0e, $f1, $10  ; frame 7, cutoff=116
    !byte $0f, $f1, $10  ; frame 8, cutoff=121
    !byte $0f, $f1, $10  ; frame 9, cutoff=127
    !byte $10, $f1, $10  ; frame 10, cutoff=132
    !byte $11, $f1, $10  ; frame 11, cutoff=137
    !byte $11, $f1, $10  ; frame 12, cutoff=143
    !byte $12, $f1, $10  ; frame 13, cutoff=148
    !byte $13, $f1, $10  ; frame 14, cutoff=154
    !byte $13, $f1, $10  ; frame 15, cutoff=159
    !byte $ff, $00, $00        ; end-of-table marker

grand_piano_freq_lo:  !byte $45
grand_piano_freq_hi:  !byte $1d
grand_piano_volume:   !byte $0f
grand_piano_gate_frames:    !byte $0a, $00
grand_piano_release_frames: !byte $9b, $00

