; ================================================================
; SID instrument: violin
; Auto-generated by sidmatch.encoders.raw_asm - do not edit by hand.
;
;   waveform         = 'saw' (mask=$20)
;   adsr             = A=1 D=6 S=4 R=6
;   pulse_width      = 3359 (pw_start=3359 pw_delta=-43 pw_mode=sweep)
;   filter           = mode='off' cutoff_start=44 cutoff_end=44 sweep_frames=50 res=8 voice1=0
;   wavetable        = attack_wf='pulse+saw' sustain_wf='saw' attack_frames=5 test_bit=True
;   ring_mod=0 sync=0 volume=15
;   frequency        = 440.0 Hz (sid_reg=$1d45)
;   gate_frames=15 release_frames=15
; ================================================================

; @meta waveform=saw
; @meta attack=1
; @meta decay=6
; @meta sustain=4
; @meta release=6
; @meta pulse_width=3359
; @meta filter_cutoff=44
; @meta filter_resonance=8
; @meta filter_mode=off
; @meta filter_voice1=0
; @meta ring_mod=0
; @meta sync=0
; @meta frequency=440.0
; @meta gate_frames=15
; @meta release_frames=15
; @meta volume=15
; @meta freq_reg=7493
; @meta wt_attack_frames=5
; @meta wt_attack_waveform=pulse+saw
; @meta wt_sustain_waveform=saw
; @meta wt_use_test_bit=1
; @meta pw_start=3359
; @meta pw_delta=-43
; @meta pw_min=255
; @meta pw_max=3659
; @meta pw_mode=sweep
; @meta filter_cutoff_start=44
; @meta filter_cutoff_end=44
; @meta filter_sweep_frames=50
; @meta fitness_score=0.0000
; @meta version=1
; @meta chip_model=6581
; @meta source_instrument=Philharmonia Orchestra (CC-BY-SA 3.0)
; @meta pw_table=
; @meta wavetable=

violin_adsr:
    !byte $16           ; attack<<4 | decay
    !byte $46           ; sustain<<4 | release

violin_wavetable:
    !byte $08, $00 ; test bit (reset osc)
    !byte $60, $00 ; attack wf (frame 1)
    !byte $60, $00 ; attack wf (frame 2)
    !byte $60, $00 ; attack wf (frame 3)
    !byte $60, $00 ; attack wf (frame 4)
    !byte $60, $00 ; attack wf (frame 5)
    !byte $20, $00 ; sustain wf (frame 6)
    !byte $ff, $00             ; end-of-table marker

violin_pulsetable:
    !byte $00, $d1 ; frame 0, pw=3359
    !byte $01, $cf ; frame 1, pw=3316
    !byte $02, $cc ; frame 2, pw=3273
    !byte $03, $c9 ; frame 3, pw=3230
    !byte $04, $c7 ; frame 4, pw=3187
    !byte $05, $c4 ; frame 5, pw=3144
    !byte $06, $c1 ; frame 6, pw=3101
    !byte $07, $bf ; frame 7, pw=3058
    !byte $08, $bc ; frame 8, pw=3015
    !byte $09, $b9 ; frame 9, pw=2972
    !byte $0a, $b7 ; frame 10, pw=2929
    !byte $0b, $b4 ; frame 11, pw=2886
    !byte $0c, $b1 ; frame 12, pw=2843
    !byte $0d, $af ; frame 13, pw=2800
    !byte $0e, $ac ; frame 14, pw=2757
    !byte $0f, $a9 ; frame 15, pw=2714
    !byte $ff, $00             ; end-of-table marker

violin_filtertable:
    !byte $05, $80, $00  ; cutoff_hi, res|rt, mode (static)
    !byte $ff, $00, $00        ; end-of-table marker

violin_freq_lo:  !byte $45
violin_freq_hi:  !byte $1d
violin_volume:   !byte $0f
violin_gate_frames:    !byte $0f, $00
violin_release_frames: !byte $0f, $00

