; ================================================================
; SID instrument: acoustic_guitar
; Auto-generated by sidmatch.encoders.raw_asm - do not edit by hand.
;
;   waveform         = 'saw' (mask=$20)
;   adsr             = A=3 D=8 S=12 R=12
;   pulse_width      = 3211 (pw_start=3211 pw_delta=38 pw_mode=sweep)
;   filter           = mode='lp' cutoff_start=1010 cutoff_end=300 sweep_frames=8 res=4 voice1=1
;   wavetable        = attack_wf='saw+triangle' sustain_wf='saw' attack_frames=5 test_bit=True
;   ring_mod=0 sync=0 volume=15
;   frequency        = 440.0 Hz (sid_reg=$1d45)
;   gate_frames=21 release_frames=155
; ================================================================

; @meta waveform=saw
; @meta attack=3
; @meta decay=8
; @meta sustain=12
; @meta release=12
; @meta pulse_width=3211
; @meta filter_cutoff=1010
; @meta filter_resonance=4
; @meta filter_mode=lp
; @meta filter_voice1=1
; @meta ring_mod=0
; @meta sync=0
; @meta frequency=440.0
; @meta gate_frames=21
; @meta release_frames=155
; @meta volume=15
; @meta freq_reg=7493
; @meta wt_attack_frames=5
; @meta wt_attack_waveform=saw+triangle
; @meta wt_sustain_waveform=saw
; @meta wt_use_test_bit=1
; @meta pw_start=3211
; @meta pw_delta=38
; @meta pw_min=2705
; @meta pw_max=2918
; @meta pw_mode=sweep
; @meta filter_cutoff_start=1010
; @meta filter_cutoff_end=300
; @meta filter_sweep_frames=8
; @meta fitness_score=0.0000
; @meta version=4
; @meta chip_model=6581
; @meta source_instrument=Philharmonia Orchestra (CC-BY-SA 3.0)
; @meta pw_table=
; @meta wavetable=

acoustic_guitar_adsr:
    !byte $38           ; attack<<4 | decay
    !byte $cc           ; sustain<<4 | release

acoustic_guitar_wavetable:
    !byte $08, $00 ; test bit (reset osc)
    !byte $30, $00 ; attack wf (frame 1)
    !byte $30, $00 ; attack wf (frame 2)
    !byte $30, $00 ; attack wf (frame 3)
    !byte $30, $00 ; attack wf (frame 4)
    !byte $30, $00 ; attack wf (frame 5)
    !byte $20, $00 ; sustain wf (frame 6)
    !byte $ff, $00             ; end-of-table marker

acoustic_guitar_pulsetable:
    !byte $00, $b6 ; frame 0, pw=2918
    !byte $01, $b6 ; frame 1, pw=2918
    !byte $02, $b6 ; frame 2, pw=2918
    !byte $03, $b6 ; frame 3, pw=2918
    !byte $04, $b6 ; frame 4, pw=2918
    !byte $05, $b6 ; frame 5, pw=2918
    !byte $06, $b6 ; frame 6, pw=2918
    !byte $07, $b6 ; frame 7, pw=2918
    !byte $08, $b6 ; frame 8, pw=2918
    !byte $09, $b6 ; frame 9, pw=2918
    !byte $0a, $b6 ; frame 10, pw=2918
    !byte $0b, $b6 ; frame 11, pw=2918
    !byte $0c, $b6 ; frame 12, pw=2918
    !byte $0d, $b6 ; frame 13, pw=2918
    !byte $0e, $b6 ; frame 14, pw=2918
    !byte $0f, $b6 ; frame 15, pw=2918
    !byte $ff, $00             ; end-of-table marker

acoustic_guitar_filtertable:
    !byte $7e, $41, $10  ; frame 0, cutoff=1010
    !byte $73, $41, $10  ; frame 1, cutoff=921
    !byte $68, $41, $10  ; frame 2, cutoff=832
    !byte $5d, $41, $10  ; frame 3, cutoff=744
    !byte $51, $41, $10  ; frame 4, cutoff=655
    !byte $46, $41, $10  ; frame 5, cutoff=566
    !byte $3b, $41, $10  ; frame 6, cutoff=478
    !byte $30, $41, $10  ; frame 7, cutoff=389
    !byte $25, $41, $10  ; frame 8, cutoff=300
    !byte $ff, $00, $00        ; end-of-table marker

acoustic_guitar_freq_lo:  !byte $45
acoustic_guitar_freq_hi:  !byte $1d
acoustic_guitar_volume:   !byte $0f
acoustic_guitar_gate_frames:    !byte $15, $00
acoustic_guitar_release_frames: !byte $9b, $00

