; ================================================================
; SID instrument: acoustic_guitar
; Auto-generated by sidmatch.encoders.raw_asm - do not edit by hand.
;
;   waveform         = 'saw' (mask=$20)
;   adsr             = A=0 D=3 S=2 R=14
;   pulse_width      = 3605 (pw_start=3605 pw_delta=-35 pw_mode=sweep)
;   filter           = mode='off' cutoff_start=44 cutoff_end=44 sweep_frames=50 res=8 voice1=0
;   wavetable        = attack_wf='pulse+saw' sustain_wf='saw' attack_frames=3 test_bit=False
;   ring_mod=0 sync=0 volume=15
;   frequency        = 440.0 Hz (sid_reg=$1d45)
;   gate_frames=10 release_frames=250
; ================================================================

; @meta waveform=saw
; @meta attack=0
; @meta decay=3
; @meta sustain=2
; @meta release=14
; @meta pulse_width=3605
; @meta filter_cutoff=44
; @meta filter_resonance=8
; @meta filter_mode=off
; @meta filter_voice1=0
; @meta ring_mod=0
; @meta sync=0
; @meta frequency=440.0
; @meta gate_frames=10
; @meta release_frames=250
; @meta volume=15
; @meta freq_reg=7493
; @meta wt_attack_frames=3
; @meta wt_attack_waveform=pulse+saw
; @meta wt_sustain_waveform=saw
; @meta wt_use_test_bit=0
; @meta pw_start=3605
; @meta pw_delta=-35
; @meta pw_min=0
; @meta pw_max=2469
; @meta pw_mode=sweep
; @meta filter_cutoff_start=44
; @meta filter_cutoff_end=44
; @meta filter_sweep_frames=50
; @meta fitness_score=0.0000
; @meta version=5
; @meta chip_model=6581
; @meta source_instrument=Philharmonia Orchestra (CC-BY-SA 3.0)
; @meta pw_table=
; @meta wavetable=

acoustic_guitar_adsr:
    !byte $03           ; attack<<4 | decay
    !byte $2e           ; sustain<<4 | release

acoustic_guitar_wavetable:
    !byte $60, $00 ; attack wf (frame 0)
    !byte $60, $00 ; attack wf (frame 1)
    !byte $60, $00 ; attack wf (frame 2)
    !byte $60, $00 ; attack wf (frame 3)
    !byte $20, $00 ; sustain wf (frame 4)
    !byte $ff, $00             ; end-of-table marker

acoustic_guitar_pulsetable:
    !byte $00, $9a ; frame 0, pw=2469
    !byte $01, $9a ; frame 1, pw=2469
    !byte $02, $9a ; frame 2, pw=2469
    !byte $03, $9a ; frame 3, pw=2469
    !byte $04, $9a ; frame 4, pw=2469
    !byte $05, $9a ; frame 5, pw=2469
    !byte $06, $9a ; frame 6, pw=2469
    !byte $07, $9a ; frame 7, pw=2469
    !byte $08, $9a ; frame 8, pw=2469
    !byte $09, $9a ; frame 9, pw=2469
    !byte $0a, $9a ; frame 10, pw=2469
    !byte $0b, $9a ; frame 11, pw=2469
    !byte $0c, $9a ; frame 12, pw=2469
    !byte $0d, $9a ; frame 13, pw=2469
    !byte $0e, $9a ; frame 14, pw=2469
    !byte $0f, $9a ; frame 15, pw=2469
    !byte $ff, $00             ; end-of-table marker

acoustic_guitar_filtertable:
    !byte $05, $80, $00  ; cutoff_hi, res|rt, mode (static)
    !byte $ff, $00, $00        ; end-of-table marker

acoustic_guitar_freq_lo:  !byte $45
acoustic_guitar_freq_hi:  !byte $1d
acoustic_guitar_volume:   !byte $0f
acoustic_guitar_gate_frames:    !byte $0a, $00
acoustic_guitar_release_frames: !byte $fa, $00

