; ================================================================
; SID instrument: acoustic_guitar
; Auto-generated by sidmatch.encoders.raw_asm - do not edit by hand.
;
;   waveform         = 'pulse' (mask=$40)
;   adsr             = A=4 D=9 S=10 R=4
;   pulse_width      = 3810 (pw_start=3810 pw_delta=-24 pw_mode=sweep)
;   filter           = mode='lp' cutoff_start=383 cutoff_end=390 sweep_frames=65 res=4 voice1=1
;   wavetable        = attack_wf='pulse' sustain_wf='pulse' attack_frames=2 test_bit=False
;   ring_mod=0 sync=0 volume=15
;   frequency        = 329.63 Hz (sid_reg=$15ed)
;   gate_frames=44 release_frames=10
; ================================================================

; @meta waveform=pulse
; @meta attack=4
; @meta decay=9
; @meta sustain=10
; @meta release=4
; @meta pulse_width=3810
; @meta filter_cutoff=383
; @meta filter_resonance=4
; @meta filter_mode=lp
; @meta filter_voice1=1
; @meta ring_mod=0
; @meta sync=0
; @meta frequency=329.63
; @meta gate_frames=44
; @meta release_frames=10
; @meta volume=15
; @meta freq_reg=5613
; @meta wt_attack_frames=2
; @meta wt_attack_waveform=
; @meta wt_sustain_waveform=pulse
; @meta wt_use_test_bit=0
; @meta pw_start=3810
; @meta pw_delta=-24
; @meta pw_min=993
; @meta pw_max=1286
; @meta pw_mode=sweep
; @meta filter_cutoff_start=383
; @meta filter_cutoff_end=390
; @meta filter_sweep_frames=65
; @meta fitness_score=0.2944
; @meta version=2
; @meta chip_model=6581
; @meta source_instrument=Philharmonia Orchestra, acoustic guitar E4 forte (CC-BY-SA 3.0)
; @meta pw_table=
; @meta wavetable=

acoustic_guitar_adsr:
    !byte $49           ; attack<<4 | decay
    !byte $a4           ; sustain<<4 | release

acoustic_guitar_wavetable:
    !byte $40, $00 ; attack wf (frame 0)
    !byte $40, $01 ; attack wf (frame 1)
    !byte $40, $02 ; attack wf (frame 2)
    !byte $40, $03 ; sustain wf (frame 3)
    !byte $ff, $00             ; end-of-table marker

acoustic_guitar_pulsetable:
    !byte $00, $50 ; frame 0, pw=1286
    !byte $01, $50 ; frame 1, pw=1286
    !byte $02, $50 ; frame 2, pw=1286
    !byte $03, $50 ; frame 3, pw=1286
    !byte $04, $50 ; frame 4, pw=1286
    !byte $05, $50 ; frame 5, pw=1286
    !byte $06, $50 ; frame 6, pw=1286
    !byte $07, $50 ; frame 7, pw=1286
    !byte $08, $50 ; frame 8, pw=1286
    !byte $09, $50 ; frame 9, pw=1286
    !byte $0a, $50 ; frame 10, pw=1286
    !byte $0b, $50 ; frame 11, pw=1286
    !byte $0c, $50 ; frame 12, pw=1286
    !byte $0d, $50 ; frame 13, pw=1286
    !byte $0e, $50 ; frame 14, pw=1286
    !byte $0f, $50 ; frame 15, pw=1286
    !byte $ff, $00             ; end-of-table marker

acoustic_guitar_filtertable:
    !byte $2f, $41, $10  ; frame 0, cutoff=383
    !byte $2f, $41, $10  ; frame 1, cutoff=383
    !byte $2f, $41, $10  ; frame 2, cutoff=383
    !byte $2f, $41, $10  ; frame 3, cutoff=383
    !byte $2f, $41, $10  ; frame 4, cutoff=383
    !byte $30, $41, $10  ; frame 5, cutoff=384
    !byte $30, $41, $10  ; frame 6, cutoff=384
    !byte $30, $41, $10  ; frame 7, cutoff=384
    !byte $30, $41, $10  ; frame 8, cutoff=384
    !byte $30, $41, $10  ; frame 9, cutoff=384
    !byte $30, $41, $10  ; frame 10, cutoff=384
    !byte $30, $41, $10  ; frame 11, cutoff=384
    !byte $30, $41, $10  ; frame 12, cutoff=384
    !byte $30, $41, $10  ; frame 13, cutoff=384
    !byte $30, $41, $10  ; frame 14, cutoff=385
    !byte $30, $41, $10  ; frame 15, cutoff=385
    !byte $ff, $00, $00        ; end-of-table marker

acoustic_guitar_freq_lo:  !byte $ed
acoustic_guitar_freq_hi:  !byte $15
acoustic_guitar_volume:   !byte $0f
acoustic_guitar_gate_frames:    !byte $2c, $00
acoustic_guitar_release_frames: !byte $0a, $00

