; ================================================================
; SID instrument: grand_piano
; Auto-generated by sidmatch.encoders.raw_asm - do not edit by hand.
;
;   waveform         = 'pulse' (mask=$40)
;   adsr             = A=11 D=11 S=12 R=5
;   pulse_width      = 1528 (pw_table entries=4)
;   filter           = mode='lp' cutoff=310 res=10 voice1=1
;   ring_mod=0 sync=0 volume=15
;   frequency        = 261.63 Hz (sid_reg=$1167)
;   gate_frames=50 release_frames=50
;   wavetable entries = 0
; ================================================================

; @meta waveform=pulse
; @meta attack=11
; @meta decay=11
; @meta sustain=12
; @meta release=5
; @meta pulse_width=1528
; @meta filter_cutoff=310
; @meta filter_resonance=10
; @meta filter_mode=lp
; @meta filter_voice1=1
; @meta ring_mod=0
; @meta sync=0
; @meta frequency=261.63
; @meta gate_frames=50
; @meta release_frames=50
; @meta volume=15
; @meta freq_reg=4455
; @meta pw_table=0,959;16,1088;32,1024;49,3619
; @meta wavetable=
; @meta fitness_score=0.4369
; @meta version=1
; @meta chip_model=6581
; @meta source_instrument=Salamander Grand Piano V3, C4 fortissimo (CC-BY 3.0, Alexander Holm)

grand_piano_adsr:
    !byte $bb           ; attack<<4 | decay
    !byte $c5           ; sustain<<4 | release

grand_piano_wavetable:
    !byte $40, $00     ; static waveform, no cmd
    !byte $ff, $00             ; end-of-table marker

grand_piano_pulsetable:
    !byte $00, $3b ; frame 0, pw=959
    !byte $10, $44 ; frame 16, pw=1088
    !byte $20, $40 ; frame 32, pw=1024
    !byte $31, $e2 ; frame 49, pw=3619
    !byte $ff, $00             ; end-of-table marker

grand_piano_filtertable:
    !byte $26, $a1, $10  ; cutoff_hi, res|rt, mode
    !byte $ff, $00, $00        ; end-of-table marker

grand_piano_freq_lo:  !byte $67
grand_piano_freq_hi:  !byte $11
grand_piano_volume:   !byte $0f
grand_piano_gate_frames:    !byte $32, $00
grand_piano_release_frames: !byte $32, $00

