; ================================================================
; SID instrument: grand_piano
; Auto-generated by sidmatch.encoders.raw_asm - do not edit by hand.
;
;   waveform         = 'saw' (mask=$20)
;   adsr             = A=0 D=6 S=15 R=7
;   pulse_width      = 141 (pw_table entries=0)
;   filter           = mode='bp' cutoff=72 res=15 voice1=1
;   ring_mod=0 sync=0 volume=15
;   frequency        = 261.63 Hz (sid_reg=$1167)
;   gate_frames=50 release_frames=50
;   wavetable entries = 0
; ================================================================

; @meta waveform=saw
; @meta attack=0
; @meta decay=6
; @meta sustain=15
; @meta release=7
; @meta pulse_width=141
; @meta filter_cutoff=72
; @meta filter_resonance=15
; @meta filter_mode=bp
; @meta filter_voice1=1
; @meta ring_mod=0
; @meta sync=0
; @meta frequency=261.63
; @meta gate_frames=50
; @meta release_frames=50
; @meta volume=15
; @meta freq_reg=4455
; @meta fitness_score=0.3428
; @meta version=2
; @meta chip_model=8580
; @meta source_instrument=Salamander Grand Piano V3, C4 fortissimo (CC-BY 3.0, Alexander Holm)
; @meta pw_table=
; @meta wavetable=

grand_piano_adsr:
    !byte $06           ; attack<<4 | decay
    !byte $f7           ; sustain<<4 | release

grand_piano_wavetable:
    !byte $20, $00     ; static waveform, no cmd
    !byte $ff, $00             ; end-of-table marker

grand_piano_pulsetable:
    !byte $00, $08       ; absolute PW = 141
    !byte $ff, $00             ; end-of-table marker

grand_piano_filtertable:
    !byte $09, $f1, $20  ; cutoff_hi, res|rt, mode
    !byte $ff, $00, $00        ; end-of-table marker

grand_piano_freq_lo:  !byte $67
grand_piano_freq_hi:  !byte $11
grand_piano_volume:   !byte $0f
grand_piano_gate_frames:    !byte $32, $00
grand_piano_release_frames: !byte $32, $00

