; ================================================================
; SID instrument: grand_piano
; Auto-generated by sidmatch.encoders.raw_asm - do not edit by hand.
;
;   waveform         = 'saw' (mask=$20)
;   adsr             = A=1 D=9 S=6 R=3
;   pulse_width      = 2429 (pw_start=2429 pw_delta=1 pw_mode=sweep)
;   filter           = mode='lp' cutoff_start=2035 cutoff_end=291 sweep_frames=43 res=15 voice1=1
;   wavetable        = attack_wf='pulse+saw' sustain_wf='saw' attack_frames=2 test_bit=False
;   ring_mod=0 sync=0 volume=15
;   frequency        = 440.0 Hz (sid_reg=$1d45)
;   gate_frames=42 release_frames=10
; ================================================================

; @meta waveform=saw
; @meta attack=1
; @meta decay=9
; @meta sustain=6
; @meta release=3
; @meta pulse_width=2429
; @meta filter_cutoff=2035
; @meta filter_resonance=15
; @meta filter_mode=lp
; @meta filter_voice1=1
; @meta ring_mod=0
; @meta sync=0
; @meta frequency=440.0
; @meta gate_frames=42
; @meta release_frames=10
; @meta volume=15
; @meta freq_reg=7493
; @meta wt_attack_frames=2
; @meta wt_attack_waveform=pulse+saw
; @meta wt_sustain_waveform=saw
; @meta wt_use_test_bit=0
; @meta pw_start=2429
; @meta pw_delta=1
; @meta pw_min=0
; @meta pw_max=2540
; @meta pw_mode=sweep
; @meta filter_cutoff_start=2035
; @meta filter_cutoff_end=291
; @meta filter_sweep_frames=43
; @meta fitness_score=0.0000
; @meta version=10
; @meta chip_model=8580
; @meta source_instrument=Salamander Grand Piano (CC-BY 3.0)
; @meta pw_table=
; @meta wavetable=

grand_piano_adsr:
    !byte $19           ; attack<<4 | decay
    !byte $63           ; sustain<<4 | release

grand_piano_wavetable:
    !byte $60, $00 ; attack wf (frame 0)
    !byte $60, $00 ; attack wf (frame 1)
    !byte $60, $00 ; attack wf (frame 2)
    !byte $20, $00 ; sustain wf (frame 3)
    !byte $ff, $00             ; end-of-table marker

grand_piano_pulsetable:
    !byte $00, $97 ; frame 0, pw=2429
    !byte $01, $97 ; frame 1, pw=2430
    !byte $02, $97 ; frame 2, pw=2431
    !byte $03, $98 ; frame 3, pw=2432
    !byte $04, $98 ; frame 4, pw=2433
    !byte $05, $98 ; frame 5, pw=2434
    !byte $06, $98 ; frame 6, pw=2435
    !byte $07, $98 ; frame 7, pw=2436
    !byte $ff, $00             ; end-of-table marker

grand_piano_filtertable:
    !byte $fe, $f1, $10  ; frame 0, cutoff=2035
    !byte $f9, $f1, $10  ; frame 1, cutoff=1994
    !byte $f4, $f1, $10  ; frame 2, cutoff=1954
    !byte $ef, $f1, $10  ; frame 3, cutoff=1913
    !byte $ea, $f1, $10  ; frame 4, cutoff=1873
    !byte $e5, $f1, $10  ; frame 5, cutoff=1832
    !byte $e0, $f1, $10  ; frame 6, cutoff=1792
    !byte $da, $f1, $10  ; frame 7, cutoff=1751
    !byte $d5, $f1, $10  ; frame 8, cutoff=1711
    !byte $d0, $f1, $10  ; frame 9, cutoff=1670
    !byte $cb, $f1, $10  ; frame 10, cutoff=1629
    !byte $c6, $f1, $10  ; frame 11, cutoff=1589
    !byte $c1, $f1, $10  ; frame 12, cutoff=1548
    !byte $bc, $f1, $10  ; frame 13, cutoff=1508
    !byte $b7, $f1, $10  ; frame 14, cutoff=1467
    !byte $b2, $f1, $10  ; frame 15, cutoff=1427
    !byte $ff, $00, $00        ; end-of-table marker

grand_piano_freq_lo:  !byte $45
grand_piano_freq_hi:  !byte $1d
grand_piano_volume:   !byte $0f
grand_piano_gate_frames:    !byte $2a, $00
grand_piano_release_frames: !byte $0a, $00

