; ================================================================
; SID instrument: grand_piano
; Auto-generated by sidmatch.encoders.raw_asm - do not edit by hand.
;
;   waveform         = 'saw' (mask=$20)
;   adsr             = A=2 D=6 S=15 R=12
;   pulse_width      = 4033 (pw_start=4033 pw_delta=-48 pw_mode=sweep)
;   filter           = mode='lp' cutoff_start=210 cutoff_end=153 sweep_frames=90 res=3 voice1=1
;   wavetable        = attack_wf='pulse+saw' sustain_wf='saw' attack_frames=5 test_bit=True
;   ring_mod=0 sync=0 volume=15
;   frequency        = 440.0 Hz (sid_reg=$1d45)
;   gate_frames=16 release_frames=155
; ================================================================

; @meta waveform=saw
; @meta attack=2
; @meta decay=6
; @meta sustain=15
; @meta release=12
; @meta pulse_width=4033
; @meta filter_cutoff=210
; @meta filter_resonance=3
; @meta filter_mode=lp
; @meta filter_voice1=1
; @meta ring_mod=0
; @meta sync=0
; @meta frequency=440.0
; @meta gate_frames=16
; @meta release_frames=155
; @meta volume=15
; @meta freq_reg=7493
; @meta wt_attack_frames=5
; @meta wt_attack_waveform=pulse+saw
; @meta wt_sustain_waveform=saw
; @meta wt_use_test_bit=1
; @meta pw_start=4033
; @meta pw_delta=-48
; @meta pw_min=901
; @meta pw_max=1460
; @meta pw_mode=sweep
; @meta filter_cutoff_start=210
; @meta filter_cutoff_end=153
; @meta filter_sweep_frames=90
; @meta fitness_score=0.4720
; @meta version=15
; @meta chip_model=8580
; @meta source_instrument=Salamander Grand Piano (CC-BY 3.0)
; @meta pw_table=
; @meta wavetable=

grand_piano_adsr:
    !byte $26           ; attack<<4 | decay
    !byte $fc           ; sustain<<4 | release

grand_piano_wavetable:
    !byte $08, $00 ; test bit (reset osc)
    !byte $60, $00 ; attack wf (frame 1)
    !byte $60, $00 ; attack wf (frame 2)
    !byte $60, $00 ; attack wf (frame 3)
    !byte $60, $00 ; attack wf (frame 4)
    !byte $60, $00 ; attack wf (frame 5)
    !byte $20, $00 ; sustain wf (frame 6)
    !byte $ff, $00             ; end-of-table marker

grand_piano_pulsetable:
    !byte $00, $5b ; frame 0, pw=1460
    !byte $01, $5b ; frame 1, pw=1460
    !byte $02, $5b ; frame 2, pw=1460
    !byte $03, $5b ; frame 3, pw=1460
    !byte $04, $5b ; frame 4, pw=1460
    !byte $05, $5b ; frame 5, pw=1460
    !byte $06, $5b ; frame 6, pw=1460
    !byte $07, $5b ; frame 7, pw=1460
    !byte $08, $5b ; frame 8, pw=1460
    !byte $09, $5b ; frame 9, pw=1460
    !byte $0a, $5b ; frame 10, pw=1460
    !byte $0b, $5b ; frame 11, pw=1460
    !byte $0c, $5b ; frame 12, pw=1460
    !byte $0d, $5b ; frame 13, pw=1460
    !byte $0e, $5b ; frame 14, pw=1460
    !byte $0f, $5b ; frame 15, pw=1460
    !byte $ff, $00             ; end-of-table marker

grand_piano_filtertable:
    !byte $1a, $31, $10  ; frame 0, cutoff=210
    !byte $1a, $31, $10  ; frame 1, cutoff=209
    !byte $1a, $31, $10  ; frame 2, cutoff=209
    !byte $1a, $31, $10  ; frame 3, cutoff=208
    !byte $19, $31, $10  ; frame 4, cutoff=207
    !byte $19, $31, $10  ; frame 5, cutoff=207
    !byte $19, $31, $10  ; frame 6, cutoff=206
    !byte $19, $31, $10  ; frame 7, cutoff=206
    !byte $19, $31, $10  ; frame 8, cutoff=205
    !byte $19, $31, $10  ; frame 9, cutoff=204
    !byte $19, $31, $10  ; frame 10, cutoff=204
    !byte $19, $31, $10  ; frame 11, cutoff=203
    !byte $19, $31, $10  ; frame 12, cutoff=202
    !byte $19, $31, $10  ; frame 13, cutoff=202
    !byte $19, $31, $10  ; frame 14, cutoff=201
    !byte $19, $31, $10  ; frame 15, cutoff=200
    !byte $ff, $00, $00        ; end-of-table marker

grand_piano_freq_lo:  !byte $45
grand_piano_freq_hi:  !byte $1d
grand_piano_volume:   !byte $0f
grand_piano_gate_frames:    !byte $10, $00
grand_piano_release_frames: !byte $9b, $00

