; ================================================================
; SID instrument: grand_piano
; Auto-generated by sidmatch.encoders.raw_asm - do not edit by hand.
;
;   waveform         = 'pulse' (mask=$40)
;   adsr             = A=0 D=9 S=0 R=9
;   pulse_width      = 6 (pw_start=6 pw_delta=-28 pw_mode=sweep)
;   filter           = mode='off' cutoff_start=44 cutoff_end=44 sweep_frames=50 res=8 voice1=0
;   wavetable        = attack_wf='noise' sustain_wf='pulse' attack_frames=5 test_bit=True
;   ring_mod=0 sync=0 volume=15
;   frequency        = 440.0 Hz (sid_reg=$1d45)
;   gate_frames=100 release_frames=42
; ================================================================

; @meta waveform=pulse
; @meta attack=0
; @meta decay=9
; @meta sustain=0
; @meta release=9
; @meta pulse_width=6
; @meta filter_cutoff=44
; @meta filter_resonance=8
; @meta filter_mode=off
; @meta filter_voice1=0
; @meta ring_mod=0
; @meta sync=0
; @meta frequency=440.0
; @meta gate_frames=100
; @meta release_frames=42
; @meta volume=15
; @meta freq_reg=7493
; @meta wt_attack_frames=5
; @meta wt_attack_waveform=noise
; @meta wt_sustain_waveform=pulse
; @meta wt_use_test_bit=1
; @meta pw_start=6
; @meta pw_delta=-28
; @meta pw_min=0
; @meta pw_max=1487
; @meta pw_mode=sweep
; @meta filter_cutoff_start=44
; @meta filter_cutoff_end=44
; @meta filter_sweep_frames=50
; @meta fitness_score=0.0000
; @meta version=16
; @meta chip_model=8580
; @meta pw_table=
; @meta wavetable=

grand_piano_adsr:
    !byte $09           ; attack<<4 | decay
    !byte $09           ; sustain<<4 | release

grand_piano_wavetable:
    !byte $08, $00 ; test bit (reset osc)
    !byte $80, $00 ; attack wf (frame 1)
    !byte $80, $00 ; attack wf (frame 2)
    !byte $80, $00 ; attack wf (frame 3)
    !byte $80, $00 ; attack wf (frame 4)
    !byte $80, $00 ; attack wf (frame 5)
    !byte $40, $00 ; sustain wf (frame 6)
    !byte $ff, $00             ; end-of-table marker

grand_piano_pulsetable:
    !byte $00, $00 ; frame 0, pw=6
    !byte $01, $00 ; frame 1, pw=0
    !byte $02, $00 ; frame 2, pw=0
    !byte $03, $00 ; frame 3, pw=0
    !byte $04, $00 ; frame 4, pw=0
    !byte $05, $00 ; frame 5, pw=0
    !byte $06, $00 ; frame 6, pw=0
    !byte $07, $00 ; frame 7, pw=0
    !byte $08, $00 ; frame 8, pw=0
    !byte $09, $00 ; frame 9, pw=0
    !byte $0a, $00 ; frame 10, pw=0
    !byte $0b, $00 ; frame 11, pw=0
    !byte $0c, $00 ; frame 12, pw=0
    !byte $0d, $00 ; frame 13, pw=0
    !byte $0e, $00 ; frame 14, pw=0
    !byte $0f, $00 ; frame 15, pw=0
    !byte $ff, $00             ; end-of-table marker

grand_piano_filtertable:
    !byte $05, $80, $00  ; cutoff_hi, res|rt, mode (static)
    !byte $ff, $00, $00        ; end-of-table marker

grand_piano_freq_lo:  !byte $45
grand_piano_freq_hi:  !byte $1d
grand_piano_volume:   !byte $0f
grand_piano_gate_frames:    !byte $64, $00
grand_piano_release_frames: !byte $2a, $00

