; ================================================================
; SID instrument: grand_piano
; Auto-generated by sidmatch.encoders.raw_asm - do not edit by hand.
;
;   waveform         = 'saw' (mask=$20)
;   adsr             = A=12 D=6 S=7 R=8
;   pulse_width      = 900 (pw_start=900 pw_delta=-1 pw_mode=sweep)
;   filter           = mode='lp' cutoff_start=426 cutoff_end=166 sweep_frames=18 res=4 voice1=1
;   wavetable        = attack_wf='pulse+saw' sustain_wf='saw' attack_frames=5 test_bit=False
;   ring_mod=0 sync=0 volume=15
;   frequency        = 440.0 Hz (sid_reg=$1d45)
;   gate_frames=65 release_frames=20
; ================================================================

; @meta waveform=saw
; @meta attack=12
; @meta decay=6
; @meta sustain=7
; @meta release=8
; @meta pulse_width=900
; @meta filter_cutoff=426
; @meta filter_resonance=4
; @meta filter_mode=lp
; @meta filter_voice1=1
; @meta ring_mod=0
; @meta sync=0
; @meta frequency=440.0
; @meta gate_frames=65
; @meta release_frames=20
; @meta volume=15
; @meta freq_reg=7493
; @meta wt_attack_frames=5
; @meta wt_attack_waveform=pulse+saw
; @meta wt_sustain_waveform=saw
; @meta wt_use_test_bit=0
; @meta pw_start=900
; @meta pw_delta=-1
; @meta pw_min=2150
; @meta pw_max=3912
; @meta pw_mode=sweep
; @meta filter_cutoff_start=426
; @meta filter_cutoff_end=166
; @meta filter_sweep_frames=18
; @meta fitness_score=0.0000
; @meta version=5
; @meta chip_model=8580
; @meta pw_table=
; @meta wavetable=

grand_piano_adsr:
    !byte $c6           ; attack<<4 | decay
    !byte $78           ; sustain<<4 | release

grand_piano_wavetable:
    !byte $60, $00 ; attack wf (frame 0)
    !byte $60, $00 ; attack wf (frame 1)
    !byte $60, $00 ; attack wf (frame 2)
    !byte $60, $00 ; attack wf (frame 3)
    !byte $60, $00 ; attack wf (frame 4)
    !byte $60, $00 ; attack wf (frame 5)
    !byte $20, $00 ; sustain wf (frame 6)
    !byte $ff, $00             ; end-of-table marker

grand_piano_pulsetable:
    !byte $00, $86 ; frame 0, pw=2150
    !byte $01, $86 ; frame 1, pw=2150
    !byte $02, $86 ; frame 2, pw=2150
    !byte $03, $86 ; frame 3, pw=2150
    !byte $04, $86 ; frame 4, pw=2150
    !byte $05, $86 ; frame 5, pw=2150
    !byte $06, $86 ; frame 6, pw=2150
    !byte $07, $86 ; frame 7, pw=2150
    !byte $ff, $00             ; end-of-table marker

grand_piano_filtertable:
    !byte $35, $41, $10  ; frame 0, cutoff=426
    !byte $33, $41, $10  ; frame 1, cutoff=412
    !byte $31, $41, $10  ; frame 2, cutoff=397
    !byte $2f, $41, $10  ; frame 3, cutoff=383
    !byte $2e, $41, $10  ; frame 4, cutoff=368
    !byte $2c, $41, $10  ; frame 5, cutoff=354
    !byte $2a, $41, $10  ; frame 6, cutoff=339
    !byte $28, $41, $10  ; frame 7, cutoff=325
    !byte $26, $41, $10  ; frame 8, cutoff=310
    !byte $25, $41, $10  ; frame 9, cutoff=296
    !byte $23, $41, $10  ; frame 10, cutoff=282
    !byte $21, $41, $10  ; frame 11, cutoff=267
    !byte $1f, $41, $10  ; frame 12, cutoff=253
    !byte $1d, $41, $10  ; frame 13, cutoff=238
    !byte $1c, $41, $10  ; frame 14, cutoff=224
    !byte $1a, $41, $10  ; frame 15, cutoff=209
    !byte $ff, $00, $00        ; end-of-table marker

grand_piano_freq_lo:  !byte $45
grand_piano_freq_hi:  !byte $1d
grand_piano_volume:   !byte $0f
grand_piano_gate_frames:    !byte $41, $00
grand_piano_release_frames: !byte $14, $00

