; ================================================================
; SID instrument: grand_piano
; Auto-generated by sidmatch.encoders.raw_asm - do not edit by hand.
;
;   waveform         = 'pulse' (mask=$40)
;   adsr             = A=1 D=6 S=14 R=10
;   pulse_width      = 672 (pw_start=672 pw_delta=41 pw_mode=sweep)
;   filter           = mode='lp' cutoff_start=63 cutoff_end=320 sweep_frames=100 res=15 voice1=1
;   wavetable        = attack_wf='pulse+saw' sustain_wf='pulse' attack_frames=1 test_bit=True
;   ring_mod=0 sync=0 volume=15
;   frequency        = 261.63 Hz (sid_reg=$1167)
;   gate_frames=15 release_frames=80
; ================================================================

; @meta waveform=pulse
; @meta attack=1
; @meta decay=6
; @meta sustain=14
; @meta release=10
; @meta pulse_width=672
; @meta filter_cutoff=63
; @meta filter_resonance=15
; @meta filter_mode=lp
; @meta filter_voice1=1
; @meta ring_mod=0
; @meta sync=0
; @meta frequency=261.63
; @meta gate_frames=15
; @meta release_frames=80
; @meta volume=15
; @meta freq_reg=4455
; @meta wt_attack_frames=1
; @meta wt_attack_waveform=pulse+saw
; @meta wt_sustain_waveform=pulse
; @meta wt_use_test_bit=1
; @meta pw_start=672
; @meta pw_delta=41
; @meta pw_min=370
; @meta pw_max=1300
; @meta pw_mode=sweep
; @meta filter_cutoff_start=63
; @meta filter_cutoff_end=320
; @meta filter_sweep_frames=100
; @meta fitness_score=0.2534
; @meta version=3
; @meta chip_model=8580
; @meta source_instrument=Salamander Grand Piano V3, C4 fortissimo (CC-BY 3.0, Alexander Holm)
; @meta pw_table=
; @meta wavetable=

grand_piano_adsr:
    !byte $16           ; attack<<4 | decay
    !byte $ea           ; sustain<<4 | release

grand_piano_wavetable:
    !byte $08, $00 ; test bit (reset osc)
    !byte $60, $01 ; attack wf (frame 1)
    !byte $40, $02 ; sustain wf (frame 2)
    !byte $40, $03 ; sustain wf (frame 3)
    !byte $ff, $00             ; end-of-table marker

grand_piano_pulsetable:
    !byte $00, $2a ; frame 0, pw=672
    !byte $01, $2c ; frame 1, pw=713
    !byte $02, $2f ; frame 2, pw=754
    !byte $03, $31 ; frame 3, pw=795
    !byte $04, $34 ; frame 4, pw=836
    !byte $05, $36 ; frame 5, pw=877
    !byte $06, $39 ; frame 6, pw=918
    !byte $07, $3b ; frame 7, pw=959
    !byte $08, $3e ; frame 8, pw=1000
    !byte $09, $41 ; frame 9, pw=1041
    !byte $0a, $43 ; frame 10, pw=1082
    !byte $0b, $46 ; frame 11, pw=1123
    !byte $0c, $48 ; frame 12, pw=1164
    !byte $0d, $4b ; frame 13, pw=1205
    !byte $0e, $4d ; frame 14, pw=1246
    !byte $0f, $50 ; frame 15, pw=1287
    !byte $ff, $00             ; end-of-table marker

grand_piano_filtertable:
    !byte $07, $f1, $10  ; frame 0, cutoff=63
    !byte $08, $f1, $10  ; frame 1, cutoff=66
    !byte $08, $f1, $10  ; frame 2, cutoff=68
    !byte $08, $f1, $10  ; frame 3, cutoff=71
    !byte $09, $f1, $10  ; frame 4, cutoff=73
    !byte $09, $f1, $10  ; frame 5, cutoff=76
    !byte $09, $f1, $10  ; frame 6, cutoff=78
    !byte $0a, $f1, $10  ; frame 7, cutoff=81
    !byte $0a, $f1, $10  ; frame 8, cutoff=84
    !byte $0a, $f1, $10  ; frame 9, cutoff=86
    !byte $0b, $f1, $10  ; frame 10, cutoff=89
    !byte $0b, $f1, $10  ; frame 11, cutoff=91
    !byte $0b, $f1, $10  ; frame 12, cutoff=94
    !byte $0c, $f1, $10  ; frame 13, cutoff=96
    !byte $0c, $f1, $10  ; frame 14, cutoff=99
    !byte $0c, $f1, $10  ; frame 15, cutoff=102
    !byte $ff, $00, $00        ; end-of-table marker

grand_piano_freq_lo:  !byte $67
grand_piano_freq_hi:  !byte $11
grand_piano_volume:   !byte $0f
grand_piano_gate_frames:    !byte $0f, $00
grand_piano_release_frames: !byte $50, $00

