; ================================================================
; SID instrument: grand_piano
; Auto-generated by sidmatch.encoders.raw_asm - do not edit by hand.
;
;   waveform         = 'saw' (mask=$20)
;   adsr             = A=9 D=5 S=15 R=11
;   pulse_width      = 3324 (pw_start=3324 pw_delta=-23 pw_mode=sweep)
;   filter           = mode='lp' cutoff_start=166 cutoff_end=157 sweep_frames=40 res=6 voice1=1
;   wavetable        = attack_wf='pulse+saw' sustain_wf='saw' attack_frames=3 test_bit=True
;   ring_mod=0 sync=0 volume=15
;   frequency        = 440.0 Hz (sid_reg=$1d45)
;   gate_frames=25 release_frames=125
; ================================================================

; @meta waveform=saw
; @meta attack=9
; @meta decay=5
; @meta sustain=15
; @meta release=11
; @meta pulse_width=3324
; @meta filter_cutoff=166
; @meta filter_resonance=6
; @meta filter_mode=lp
; @meta filter_voice1=1
; @meta ring_mod=0
; @meta sync=0
; @meta frequency=440.0
; @meta gate_frames=25
; @meta release_frames=125
; @meta volume=15
; @meta freq_reg=7493
; @meta wt_attack_frames=3
; @meta wt_attack_waveform=pulse+saw
; @meta wt_sustain_waveform=saw
; @meta wt_use_test_bit=1
; @meta pw_start=3324
; @meta pw_delta=-23
; @meta pw_min=334
; @meta pw_max=1061
; @meta pw_mode=sweep
; @meta filter_cutoff_start=166
; @meta filter_cutoff_end=157
; @meta filter_sweep_frames=40
; @meta fitness_score=0.0000
; @meta version=4
; @meta chip_model=8580
; @meta pw_table=
; @meta wavetable=

grand_piano_adsr:
    !byte $95           ; attack<<4 | decay
    !byte $fb           ; sustain<<4 | release

grand_piano_wavetable:
    !byte $08, $00 ; test bit (reset osc)
    !byte $60, $00 ; attack wf (frame 1)
    !byte $60, $00 ; attack wf (frame 2)
    !byte $60, $00 ; attack wf (frame 3)
    !byte $20, $00 ; sustain wf (frame 4)
    !byte $ff, $00             ; end-of-table marker

grand_piano_pulsetable:
    !byte $00, $42 ; frame 0, pw=1061
    !byte $01, $42 ; frame 1, pw=1061
    !byte $02, $42 ; frame 2, pw=1061
    !byte $03, $42 ; frame 3, pw=1061
    !byte $04, $42 ; frame 4, pw=1061
    !byte $05, $42 ; frame 5, pw=1061
    !byte $06, $42 ; frame 6, pw=1061
    !byte $07, $42 ; frame 7, pw=1061
    !byte $08, $42 ; frame 8, pw=1061
    !byte $09, $42 ; frame 9, pw=1061
    !byte $0a, $42 ; frame 10, pw=1061
    !byte $0b, $42 ; frame 11, pw=1061
    !byte $0c, $42 ; frame 12, pw=1061
    !byte $0d, $42 ; frame 13, pw=1061
    !byte $0e, $42 ; frame 14, pw=1061
    !byte $0f, $42 ; frame 15, pw=1061
    !byte $ff, $00             ; end-of-table marker

grand_piano_filtertable:
    !byte $14, $61, $10  ; frame 0, cutoff=166
    !byte $14, $61, $10  ; frame 1, cutoff=166
    !byte $14, $61, $10  ; frame 2, cutoff=166
    !byte $14, $61, $10  ; frame 3, cutoff=165
    !byte $14, $61, $10  ; frame 4, cutoff=165
    !byte $14, $61, $10  ; frame 5, cutoff=165
    !byte $14, $61, $10  ; frame 6, cutoff=165
    !byte $14, $61, $10  ; frame 7, cutoff=164
    !byte $14, $61, $10  ; frame 8, cutoff=164
    !byte $14, $61, $10  ; frame 9, cutoff=164
    !byte $14, $61, $10  ; frame 10, cutoff=164
    !byte $14, $61, $10  ; frame 11, cutoff=164
    !byte $14, $61, $10  ; frame 12, cutoff=163
    !byte $14, $61, $10  ; frame 13, cutoff=163
    !byte $14, $61, $10  ; frame 14, cutoff=163
    !byte $14, $61, $10  ; frame 15, cutoff=163
    !byte $ff, $00, $00        ; end-of-table marker

grand_piano_freq_lo:  !byte $45
grand_piano_freq_hi:  !byte $1d
grand_piano_volume:   !byte $0f
grand_piano_gate_frames:    !byte $19, $00
grand_piano_release_frames: !byte $7d, $00

