; ================================================================
; SID instrument: grand_piano_tpe
; Auto-generated by sidmatch.encoders.raw_asm - do not edit by hand.
;
;   waveform         = 'saw' (mask=$20)
;   adsr             = A=11 D=7 S=14 R=12
;   pulse_width      = 2048 (pw_start=2048 pw_delta=0 pw_mode=sweep)
;   filter           = mode='lp' cutoff_start=115 cutoff_end=44 sweep_frames=61 res=11 voice1=1
;   wavetable        = attack_wf='saw' sustain_wf='saw' attack_frames=4 test_bit=True
;   ring_mod=0 sync=0 volume=15
;   frequency        = 440.0 Hz (sid_reg=$1d45)
;   gate_frames=57 release_frames=155
; ================================================================

; @meta waveform=saw
; @meta attack=11
; @meta decay=7
; @meta sustain=14
; @meta release=12
; @meta pulse_width=2048
; @meta filter_cutoff=115
; @meta filter_resonance=11
; @meta filter_mode=lp
; @meta filter_voice1=1
; @meta ring_mod=0
; @meta sync=0
; @meta frequency=440.0
; @meta gate_frames=57
; @meta release_frames=155
; @meta volume=15
; @meta freq_reg=7493
; @meta wt_attack_frames=4
; @meta wt_attack_waveform=
; @meta wt_sustain_waveform=saw
; @meta wt_use_test_bit=1
; @meta pw_start=2048
; @meta pw_delta=0
; @meta pw_min=1024
; @meta pw_max=3071
; @meta pw_mode=sweep
; @meta filter_cutoff_start=115
; @meta filter_cutoff_end=44
; @meta filter_sweep_frames=61
; @meta fitness_score=0.0000
; @meta version=1
; @meta chip_model=8580
; @meta pw_table=
; @meta wavetable=

grand_piano_tpe_adsr:
    !byte $b7           ; attack<<4 | decay
    !byte $ec           ; sustain<<4 | release

grand_piano_tpe_wavetable:
    !byte $08, $00 ; test bit (reset osc)
    !byte $20, $00 ; attack wf (frame 1)
    !byte $20, $00 ; attack wf (frame 2)
    !byte $20, $00 ; attack wf (frame 3)
    !byte $20, $00 ; attack wf (frame 4)
    !byte $20, $00 ; sustain wf (frame 5)
    !byte $ff, $00             ; end-of-table marker

grand_piano_tpe_pulsetable:
    !byte $00, $80       ; absolute PW = 2048
    !byte $ff, $00             ; end-of-table marker

grand_piano_tpe_filtertable:
    !byte $0e, $b1, $10  ; frame 0, cutoff=115
    !byte $0e, $b1, $10  ; frame 1, cutoff=114
    !byte $0e, $b1, $10  ; frame 2, cutoff=113
    !byte $0e, $b1, $10  ; frame 3, cutoff=112
    !byte $0d, $b1, $10  ; frame 4, cutoff=110
    !byte $0d, $b1, $10  ; frame 5, cutoff=109
    !byte $0d, $b1, $10  ; frame 6, cutoff=108
    !byte $0d, $b1, $10  ; frame 7, cutoff=107
    !byte $0d, $b1, $10  ; frame 8, cutoff=106
    !byte $0d, $b1, $10  ; frame 9, cutoff=105
    !byte $0c, $b1, $10  ; frame 10, cutoff=103
    !byte $0c, $b1, $10  ; frame 11, cutoff=102
    !byte $0c, $b1, $10  ; frame 12, cutoff=101
    !byte $0c, $b1, $10  ; frame 13, cutoff=100
    !byte $0c, $b1, $10  ; frame 14, cutoff=99
    !byte $0c, $b1, $10  ; frame 15, cutoff=98
    !byte $ff, $00, $00        ; end-of-table marker

grand_piano_tpe_freq_lo:  !byte $45
grand_piano_tpe_freq_hi:  !byte $1d
grand_piano_tpe_volume:   !byte $0f
grand_piano_tpe_gate_frames:    !byte $39, $00
grand_piano_tpe_release_frames: !byte $9b, $00

