; ================================================================
; SID instrument: acoustic_guitar_tpe
; Auto-generated by sidmatch.encoders.raw_asm - do not edit by hand.
;
;   waveform         = 'saw' (mask=$20)
;   adsr             = A=2 D=2 S=1 R=12
;   pulse_width      = 3946 (pw_start=3946 pw_delta=3 pw_mode=sweep)
;   filter           = mode='off' cutoff_start=44 cutoff_end=44 sweep_frames=50 res=8 voice1=0
;   wavetable        = attack_wf='pulse+saw' sustain_wf='saw' attack_frames=5 test_bit=False
;   ring_mod=0 sync=0 volume=15
;   frequency        = 440.0 Hz (sid_reg=$1d45)
;   gate_frames=10 release_frames=155
; ================================================================

; @meta waveform=saw
; @meta attack=2
; @meta decay=2
; @meta sustain=1
; @meta release=12
; @meta pulse_width=3946
; @meta filter_cutoff=44
; @meta filter_resonance=8
; @meta filter_mode=off
; @meta filter_voice1=0
; @meta ring_mod=0
; @meta sync=0
; @meta frequency=440.0
; @meta gate_frames=10
; @meta release_frames=155
; @meta volume=15
; @meta freq_reg=7493
; @meta wt_attack_frames=5
; @meta wt_attack_waveform=pulse+saw
; @meta wt_sustain_waveform=saw
; @meta wt_use_test_bit=0
; @meta pw_start=3946
; @meta pw_delta=3
; @meta pw_min=3027
; @meta pw_max=4095
; @meta pw_mode=sweep
; @meta filter_cutoff_start=44
; @meta filter_cutoff_end=44
; @meta filter_sweep_frames=50
; @meta fitness_score=0.0000
; @meta version=1
; @meta chip_model=6581
; @meta pw_table=
; @meta wavetable=

acoustic_guitar_tpe_adsr:
    !byte $22           ; attack<<4 | decay
    !byte $1c           ; sustain<<4 | release

acoustic_guitar_tpe_wavetable:
    !byte $60, $00 ; attack wf (frame 0)
    !byte $60, $00 ; attack wf (frame 1)
    !byte $60, $00 ; attack wf (frame 2)
    !byte $60, $00 ; attack wf (frame 3)
    !byte $60, $00 ; attack wf (frame 4)
    !byte $60, $00 ; attack wf (frame 5)
    !byte $20, $00 ; sustain wf (frame 6)
    !byte $ff, $00             ; end-of-table marker

acoustic_guitar_tpe_pulsetable:
    !byte $00, $f6 ; frame 0, pw=3946
    !byte $01, $f6 ; frame 1, pw=3949
    !byte $02, $f7 ; frame 2, pw=3952
    !byte $03, $f7 ; frame 3, pw=3955
    !byte $04, $f7 ; frame 4, pw=3958
    !byte $05, $f7 ; frame 5, pw=3961
    !byte $06, $f7 ; frame 6, pw=3964
    !byte $07, $f7 ; frame 7, pw=3967
    !byte $08, $f8 ; frame 8, pw=3970
    !byte $09, $f8 ; frame 9, pw=3973
    !byte $0a, $f8 ; frame 10, pw=3976
    !byte $0b, $f8 ; frame 11, pw=3979
    !byte $0c, $f8 ; frame 12, pw=3982
    !byte $0d, $f9 ; frame 13, pw=3985
    !byte $0e, $f9 ; frame 14, pw=3988
    !byte $0f, $f9 ; frame 15, pw=3991
    !byte $ff, $00             ; end-of-table marker

acoustic_guitar_tpe_filtertable:
    !byte $05, $80, $00  ; cutoff_hi, res|rt, mode (static)
    !byte $ff, $00, $00        ; end-of-table marker

acoustic_guitar_tpe_freq_lo:  !byte $45
acoustic_guitar_tpe_freq_hi:  !byte $1d
acoustic_guitar_tpe_volume:   !byte $0f
acoustic_guitar_tpe_gate_frames:    !byte $0a, $00
acoustic_guitar_tpe_release_frames: !byte $9b, $00

