; ================================================================
; SID instrument: acoustic_guitar
; Auto-generated by sidmatch.encoders.raw_asm - do not edit by hand.
;
;   waveform         = 'saw' (mask=$20)
;   adsr             = A=7 D=11 S=3 R=15
;   pulse_width      = 942 (pw_table entries=0)
;   filter           = mode='bp' cutoff=84 res=11 voice1=1
;   ring_mod=0 sync=0 volume=15
;   frequency        = 329.63 Hz (sid_reg=$15ed)
;   gate_frames=50 release_frames=50
;   wavetable entries = 0
; ================================================================

; @meta waveform=saw
; @meta attack=7
; @meta decay=11
; @meta sustain=3
; @meta release=15
; @meta pulse_width=942
; @meta filter_cutoff=84
; @meta filter_resonance=11
; @meta filter_mode=bp
; @meta filter_voice1=1
; @meta ring_mod=0
; @meta sync=0
; @meta frequency=329.63
; @meta gate_frames=50
; @meta release_frames=50
; @meta volume=15
; @meta freq_reg=5613
; @meta pw_table=
; @meta wavetable=
; @meta fitness_score=0.2764
; @meta version=1

acoustic_guitar_adsr:
    !byte $7b           ; attack<<4 | decay
    !byte $3f           ; sustain<<4 | release

acoustic_guitar_wavetable:
    !byte $20, $00     ; static waveform, no cmd
    !byte $ff, $00             ; end-of-table marker

acoustic_guitar_pulsetable:
    !byte $00, $3a       ; absolute PW = 942
    !byte $ff, $00             ; end-of-table marker

acoustic_guitar_filtertable:
    !byte $0a, $b1, $20  ; cutoff_hi, res|rt, mode
    !byte $ff, $00, $00        ; end-of-table marker

acoustic_guitar_freq_lo:  !byte $ed
acoustic_guitar_freq_hi:  !byte $15
acoustic_guitar_volume:   !byte $0f
acoustic_guitar_gate_frames:    !byte $32, $00
acoustic_guitar_release_frames: !byte $32, $00

