; ================================================================
; SID instrument: grand_piano_tpe
; Auto-generated by sidmatch.encoders.raw_asm - do not edit by hand.
;
;   waveform         = 'saw' (mask=$20)
;   adsr             = A=8 D=10 S=0 R=4
;   pulse_width      = 2048 (pw_start=2048 pw_delta=0 pw_mode=sweep)
;   filter           = mode='off' cutoff_start=44 cutoff_end=44 sweep_frames=50 res=8 voice1=0
;   wavetable        = attack_wf='saw' sustain_wf='saw' attack_frames=1 test_bit=False
;   ring_mod=0 sync=0 volume=15
;   frequency        = 440.0 Hz (sid_reg=$1d45)
;   gate_frames=85 release_frames=10
; ================================================================

; @meta waveform=saw
; @meta attack=8
; @meta decay=10
; @meta sustain=0
; @meta release=4
; @meta pulse_width=2048
; @meta filter_cutoff=44
; @meta filter_resonance=8
; @meta filter_mode=off
; @meta filter_voice1=0
; @meta ring_mod=0
; @meta sync=0
; @meta frequency=440.0
; @meta gate_frames=85
; @meta release_frames=10
; @meta volume=15
; @meta freq_reg=7493
; @meta wt_attack_frames=1
; @meta wt_attack_waveform=
; @meta wt_sustain_waveform=saw
; @meta wt_use_test_bit=0
; @meta pw_start=2048
; @meta pw_delta=0
; @meta pw_min=1024
; @meta pw_max=3071
; @meta pw_mode=sweep
; @meta filter_cutoff_start=44
; @meta filter_cutoff_end=44
; @meta filter_sweep_frames=50
; @meta fitness_score=0.0000
; @meta version=1
; @meta chip_model=6581
; @meta pw_table=
; @meta wavetable=

grand_piano_tpe_adsr:
    !byte $8a           ; attack<<4 | decay
    !byte $04           ; sustain<<4 | release

grand_piano_tpe_wavetable:
    !byte $20, $00 ; attack wf (frame 0)
    !byte $20, $00 ; attack wf (frame 1)
    !byte $20, $00 ; sustain wf (frame 2)
    !byte $20, $00 ; sustain wf (frame 3)
    !byte $ff, $00             ; end-of-table marker

grand_piano_tpe_pulsetable:
    !byte $00, $80       ; absolute PW = 2048
    !byte $ff, $00             ; end-of-table marker

grand_piano_tpe_filtertable:
    !byte $05, $80, $00  ; cutoff_hi, res|rt, mode (static)
    !byte $ff, $00, $00        ; end-of-table marker

grand_piano_tpe_freq_lo:  !byte $45
grand_piano_tpe_freq_hi:  !byte $1d
grand_piano_tpe_volume:   !byte $0f
grand_piano_tpe_gate_frames:    !byte $55, $00
grand_piano_tpe_release_frames: !byte $0a, $00

