; ================================================================
; SID instrument: violin
; Auto-generated by sidmatch.encoders.raw_asm - do not edit by hand.
;
;   waveform         = 'saw' (mask=$20)
;   adsr             = A=8 D=4 S=15 R=1
;   pulse_width      = 1185 (pw_start=1185 pw_delta=21 pw_mode=sweep)
;   filter           = mode='off' cutoff_start=44 cutoff_end=44 sweep_frames=50 res=8 voice1=0
;   wavetable        = attack_wf='pulse+saw' sustain_wf='saw' attack_frames=4 test_bit=True
;   ring_mod=0 sync=0 volume=15
;   frequency        = 440.0 Hz (sid_reg=$1d45)
;   gate_frames=15 release_frames=10
; ================================================================

; @meta waveform=saw
; @meta attack=8
; @meta decay=4
; @meta sustain=15
; @meta release=1
; @meta pulse_width=1185
; @meta filter_cutoff=44
; @meta filter_resonance=8
; @meta filter_mode=off
; @meta filter_voice1=0
; @meta ring_mod=0
; @meta sync=0
; @meta frequency=440.0
; @meta gate_frames=15
; @meta release_frames=10
; @meta volume=15
; @meta freq_reg=7493
; @meta wt_attack_frames=4
; @meta wt_attack_waveform=pulse+saw
; @meta wt_sustain_waveform=saw
; @meta wt_use_test_bit=1
; @meta pw_start=1185
; @meta pw_delta=21
; @meta pw_min=913
; @meta pw_max=1376
; @meta pw_mode=sweep
; @meta filter_cutoff_start=44
; @meta filter_cutoff_end=44
; @meta filter_sweep_frames=50
; @meta fitness_score=0.0000
; @meta version=1
; @meta chip_model=8580
; @meta source_instrument=Philharmonia Orchestra (CC-BY-SA 3.0)
; @meta pw_table=
; @meta wavetable=

violin_adsr:
    !byte $84           ; attack<<4 | decay
    !byte $f1           ; sustain<<4 | release

violin_wavetable:
    !byte $08, $00 ; test bit (reset osc)
    !byte $60, $00 ; attack wf (frame 1)
    !byte $60, $00 ; attack wf (frame 2)
    !byte $60, $00 ; attack wf (frame 3)
    !byte $60, $00 ; attack wf (frame 4)
    !byte $20, $00 ; sustain wf (frame 5)
    !byte $ff, $00             ; end-of-table marker

violin_pulsetable:
    !byte $00, $4a ; frame 0, pw=1185
    !byte $01, $4b ; frame 1, pw=1206
    !byte $02, $4c ; frame 2, pw=1227
    !byte $03, $4e ; frame 3, pw=1248
    !byte $04, $4f ; frame 4, pw=1269
    !byte $05, $50 ; frame 5, pw=1290
    !byte $06, $51 ; frame 6, pw=1311
    !byte $07, $53 ; frame 7, pw=1332
    !byte $08, $54 ; frame 8, pw=1353
    !byte $09, $55 ; frame 9, pw=1374
    !byte $0a, $56 ; frame 10, pw=1376
    !byte $0b, $56 ; frame 11, pw=1376
    !byte $0c, $56 ; frame 12, pw=1376
    !byte $0d, $56 ; frame 13, pw=1376
    !byte $0e, $56 ; frame 14, pw=1376
    !byte $0f, $56 ; frame 15, pw=1376
    !byte $ff, $00             ; end-of-table marker

violin_filtertable:
    !byte $05, $80, $00  ; cutoff_hi, res|rt, mode (static)
    !byte $ff, $00, $00        ; end-of-table marker

violin_freq_lo:  !byte $45
violin_freq_hi:  !byte $1d
violin_volume:   !byte $0f
violin_gate_frames:    !byte $0f, $00
violin_release_frames: !byte $0a, $00

